# Briefsummary Parser

Our high throughput dft code returns text files with a summary of calculation results. Here we convert this text files to a pandas dataframe containing all the information

We use some tools developed for this propose alone. The module `Featurizer` parses the strings in the `briefsummary.dat` files and recreates information of each sample as magnetic configuration, lattice occupation signatures, etc.

# TODO: calculate formation energies and put them in the df !

In [1]:
from Tools.DatasetTools.Commoms import *
sys.path.insert(0, '/home/storage/fortimtb/CuadernoTrabajo/bopfoxfeaturizer/')
from BopFoxFeaturizer.brief_summary_parser import StructSummaryParser
dataset = 'Fe-Mo' # 'Cr-Co-W',  'Fe-Mo'

# Load Brief Summary

In [2]:
BS = StructSummaryParser(dataset).BriefSummary

need to create briefsummary list
reading list of briefsummary

In [3]:
BS

,,V,E0,B,fit,xc,encut,deltak,ncrash,nelem,...,atom_A,atom_B,atom_C,num_atom_A,num_atom_B,num_atom_C,num_atoms,Fe_pv,Mo_sv,EF
index,,,,,,,,,,,,,,,,,,,,,
Fe_pv8Mo_sv22.sigma-BBABB.FM,bulk sigma-BBABB.FM,14.954763 A,-10.004507,224.285410 GPa,murnaghan volume_relaxed,PBE-PAW,450,0.020,0,2,...,Fe_pv,Mo_sv,,8,22,0,30.0,0.266667,0.733333,0.215379
Fe_pv10Mo_sv20.sigma-ABBAB.FM,bulk sigma-ABBAB.FM,14.130625 A,-10.006896,237.907324 GPa,murnaghan volume_relaxed,PBE-PAW,450,0.020,0,2,...,Fe_pv,Mo_sv,,10,20,0,30.0,0.333333,0.666667,0.034391
Fe_pv4Mo_sv20.C36-ABBBB.FM,bulk C36-ABBBB.FM,16.270923 A,-10.007837,204.470374 GPa,murnaghan volume_relaxed,PBE-PAW,450,0.020,0,2,...,Fe_pv,Mo_sv,,4,20,0,24.0,0.166667,0.833333,0.479948
Fe_pv3Mo_sv10.mu-ABBBA.FM,bulk mu-ABBBA.FM,15.378254 A,-10.008565,402.123952 GPa,murnaghan volume_relaxed,PBE-PAW,450,0.020,0,2,...,Fe_pv,Mo_sv,,3,10,0,13.0,0.230769,0.769231,0.30749
Fe_pv5Mo_sv24.chi-AABB.FM,bulk chi-AABB.FM,15.751001 A,-10.015010,216.183583 GPa,murnaghan volume_relaxed,PBE-PAW,450,0.020,0,2,...,Fe_pv,Mo_sv,,5,24,0,29.0,0.172414,0.827586,0.457378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Fe_pv3Mo_sv10.mu-ABBBA.NM,bulk mu-ABBBA,15.125643 A,-9.973264,240.020984 GPa,murnaghan volume_relaxed,PBE-PAW,450,0.020,0,2,...,Fe_pv,Mo_sv,,3,10,0,13.0,0.230769,0.769231,0.342791
Fe_pv8Mo_sv22.sigma-BBABB.NM,bulk sigma-BBABB,14.698886 A,-9.976143,247.238692 GPa,murnaghan volume_relaxed,PBE-PAW,450,0.020,0,2,...,Fe_pv,Mo_sv,,8,22,0,30.0,0.266667,0.733333,0.243743
Fe_pv1Mo_sv3.L12-AB3.FM,bulk L12-AB3.FM,14.806728 A,-9.986411,223.435464 GPa,murnaghan volume_relaxed,PBE-PAW,450,0.020,0,2,...,Fe_pv,Mo_sv,,1,3,0,4.0,0.250000,0.750000,0.278125
Fe_pv8Mo_sv22.sigma-BBBBA.FM,bulk sigma-BBBBA.FM,15.095159 A,-9.991080,207.683558 GPa,murnaghan volume_relaxed,PBE-PAW,450,0.020,0,2,...,Fe_pv,Mo_sv,,8,22,0,30.0,0.266667,0.733333,0.228806
Fe_pv10Mo_sv20.sigma-ABBAB.NM,bulk sigma-ABBAB,14.000770 A,-9.993055,263.962788 GPa,murnaghan volume_relaxed,PBE-PAW,450,0.020,0,2,...,Fe_pv,Mo_sv,,10,20,0,30.0,0.333333,0.666667,0.048232

## Prepare targets

One target still missing is formation Energy. Some Convenience functions to do this has been set

In [4]:
from BopFoxFeaturizer.Featurizer import Featurizer

In [5]:
Features  = Featurizer(BS)

In [6]:
ground_states = Features.get_ground_states_energies()

In [7]:
BS['EF'] = Features.get_formation_energy(ground_states)

In [8]:
BS[['V0','B0','EF']]

                                      V0          B0        EF
index
Fe_pv8Mo_sv22.sigma-BBABB.FM   14.954763  224.285410  0.215379
Fe_pv10Mo_sv20.sigma-ABBAB.FM  14.130625  237.907324  0.034391
Fe_pv4Mo_sv20.C36-ABBBB.FM     16.270923  204.470374  0.479948
Fe_pv3Mo_sv10.mu-ABBBA.FM      15.378254  402.123952   0.30749
Fe_pv5Mo_sv24.chi-AABB.FM      15.751001  216.183583  0.457378
...                                  ...         ...       ...
Fe_pv3Mo_sv10.mu-ABBBA.NM      15.125643  240.020984  0.342791
Fe_pv8Mo_sv22.sigma-BBABB.NM   14.698886  247.238692  0.243743
Fe_pv1Mo_sv3.L12-AB3.FM        14.806728  223.435464  0.278125
Fe_pv8Mo_sv22.sigma-BBBBA.FM   15.095159  207.683558  0.228806
Fe_pv10Mo_sv20.sigma-ABBAB.NM  14.000770  263.962788  0.048232

[292 rows x 3 columns]

In [9]:
BS.to_pickle(f'{dataset}/ParsedBriefsummary.pkl')