#  Calculation of features from available libraries

- input curated BS

TODO: Maybe include some extra library ? 
MUST: include SOAP !

In [1]:
import sys
sys.path.insert(0, '/home/storage/fortimtb/CuadernoTrabajo/bopfoxfeaturizer/')
from GetPymatgenFeatures import *
from BopFoxFeaturizer.Featurizer import Featurizer

mmflatomic = os.path.join(case,'matminer_atomic_features.pkl')
mmfdensity = os.path.join (case, 'matminer_density_features.pkl')
mmfcomposition =  os.path.join (case,'matminer_composition_features.pkl')
mmfstructure =  os.path.join (case,'matminer_structure_features.pkl')
mmsoapfeatures = os.path.join(case, 'matminer_soap_features.pkl')

BS = pd.read_pickle('CuratedParsedBriefSummary.pkl')
BS['atoms_objects'] = pd.read_pickle('CrCoW-sorted-POSCAR-initial-rescaled-PymatgenStructures.pkl').dropna()
BS.dropna(inplace=True)

BS['chemical_formula'] = get_chemical_formula(BS)

las instrucciones aca abajo son las que disparan los errores al calcular los structure features!

In [2]:
BS['composition'] = StrToComposition().featurize_dataframe(BS, "chemical_formula")['composition']

StrToComposition:   0%|          | 0/1665 [00:00<?, ?it/s]

In [3]:
AtomicFeaturesMagpie = load_features(mmflatomic, BS, which='atomic')
DensitiFeatures= load_features(mmfdensity, BS, which='density')
CompositionFeatures = load_features(mmfcomposition, BS, which='composition')
SOAPFeatures = load_features(mmfstructure, BS, which='soap')
# SOAP doesnt work from matminer

In [4]:
StructureFeatures = load_features(mmfstructure, BS, which='structure')

In [5]:
StructureFeatures.dropna(axis=1)

                                    max packing efficiency
Co_pv6W_sv6.C14-BBA.NM                            0.647623
Co_pv6W_sv6.C14-BBA.FM                            0.647623
Cr_pv6W_sv2.D0_19-A3B.FM                          0.712095
Cr_pv6W_sv2.D0_19-A3B.NM                          0.712095
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM                0.584180
...                                                    ...
Cr_pv10W_sv3.mu-BAAAB.FM                          0.634381
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM                 0.584180
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM                 0.584180
Co_pv13W_sv16.chi-ABAB.NM                         0.565533
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM                0.584180

[1665 rows x 1 columns]

In [6]:
AtomicFeaturesMagpie.columns = AtomicFeaturesMagpie.columns.str.replace('MagpieData ','')

In [7]:
AtomicFeaturesMagpie.dropna(axis=1, inplace = True)

In [8]:
AtomicFeaturesMagpie.describe()

,minimum Number,maximum Number,range Number,mean Number,avg_dev Number,mode Number,minimum MendeleevNumber,maximum MendeleevNumber,range MendeleevNumber,mean MendeleevNumber,...,range GSmagmom,mean GSmagmom,avg_dev GSmagmom,mode GSmagmom,minimum SpaceGroupNumber,maximum SpaceGroupNumber,range SpaceGroupNumber,mean SpaceGroupNumber,avg_dev SpaceGroupNumber,mode SpaceGroupNumber
count,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,...,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.00000,1665.000000,1665.000000,1665.000000
mean,24.894895,67.363964,42.469069,46.695370,13.387501,47.036036,49.366967,56.857057,7.490090,52.778750,...,1.284348,0.500626,0.420920,0.468726,199.612613,228.642643,29.03003,217.684378,9.514019,217.081081
std,4.947841,16.417982,16.882773,15.824360,8.449581,24.003804,1.115015,2.623395,2.748698,2.128762,...,0.582607,0.445878,0.277748,0.711624,12.846756,3.519552,13.16862,10.078151,6.277913,16.591168
min,24.000000,24.000000,0.000000,24.000000,0.000000,24.000000,49.000000,49.000000,0.000000,49.000000,...,0.000000,0.000000,0.000000,0.000000,194.000000,194.000000,0.00000,194.000000,0.000000,194.000000
25%,24.000000,74.000000,47.000000,33.307692,5.859375,27.000000,49.000000,58.000000,7.000000,51.106061,...,1.548471,0.119113,0.181461,0.000000,194.000000,229.000000,35.00000,212.666667,4.101562,194.000000
50%,24.000000,74.000000,50.000000,44.615385,13.583829,27.000000,49.000000,58.000000,9.000000,52.166667,...,1.548471,0.387118,0.430131,0.000000,194.000000,229.000000,35.00000,220.250000,9.722222,229.000000
75%,24.000000,74.000000,50.000000,62.461538,21.555556,74.000000,49.000000,58.000000,9.000000,53.923077,...,1.548471,0.722620,0.688209,1.548471,194.000000,229.000000,35.00000,226.307692,15.555556,229.000000
max,74.000000,74.000000,50.000000,74.000000,24.793388,74.000000,58.000000,58.000000,9.000000,58.000000,...,1.548471,1.548471,0.774236,1.548471,229.000000,229.000000,35.00000,229.000000,17.500000,229.000000

In [9]:
DensitiFeatures.dropna(axis=1, inplace=True)

In [10]:
DensitiFeatures.describe()

           density          vpa  packing fraction
count  1665.000000  1665.000000       1665.000000
mean     15.287521    10.701618          0.998829
std       5.087256     0.407380          0.033768
min       0.649612     2.576499          0.025403
25%      11.429203    10.488771          1.000000
50%      14.675017    10.702010          1.000000
75%      18.784192    10.939619          1.000000
max      29.620964    11.494040          1.000000

In [11]:
CompositionFeatures.dropna(axis=1, inplace=True)

In [12]:
CompositionFeatures.describe()

,HOMO_energy,LUMO_energy,gap_AO,band center,max ionic char,avg ionic char,0-norm,2-norm,3-norm,5-norm,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
count,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,...,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.000000,1665.00000,1665.000000,1665.000000,1665.000000
mean,-0.207912,-0.206902,0.001010,4.185060,0.091838,0.012615,2.551351,0.755231,0.713343,0.693194,...,1.284348,0.500626,0.420920,0.468726,199.612613,228.642643,29.03003,217.684378,9.514019,217.081081
std,0.050215,0.051056,0.005883,0.147703,0.039763,0.008042,0.554624,0.137855,0.169035,0.187124,...,0.582607,0.445878,0.277748,0.711624,12.846756,3.519552,13.16862,10.078151,6.277913,16.591168
min,-0.322368,-0.322368,0.000000,3.716833,0.000000,0.000000,1.000000,0.584998,0.493242,0.435713,...,0.000000,0.000000,0.000000,0.000000,194.000000,194.000000,0.00000,194.000000,0.000000,194.000000
25%,-0.220603,-0.220603,0.000000,4.080115,0.055973,0.004929,2.000000,0.628932,0.563224,0.530175,...,1.548471,0.119113,0.181461,0.000000,194.000000,229.000000,35.00000,212.666667,4.101562,194.000000
50%,-0.220603,-0.220603,0.000000,4.199398,0.115294,0.013709,3.000000,0.707107,0.673540,0.651528,...,1.548471,0.387118,0.430131,0.000000,194.000000,229.000000,35.00000,220.250000,9.722222,229.000000
75%,-0.181413,-0.181413,0.000000,4.298091,0.115294,0.019364,3.000000,0.897130,0.890964,0.890416,...,1.548471,0.722620,0.688209,1.548471,194.000000,229.000000,35.00000,226.307692,15.555556,229.000000
max,-0.118123,-0.118123,0.054052,4.397803,0.115294,0.028585,3.000000,1.000000,1.000000,1.000000,...,1.548471,1.548471,0.774236,1.548471,229.000000,229.000000,35.00000,229.000000,17.500000,229.000000

In [13]:
SOAPFeatures.dropna(axis=1)

                                    max packing efficiency
Co_pv6W_sv6.C14-BBA.NM                            0.647623
Co_pv6W_sv6.C14-BBA.FM                            0.647623
Cr_pv6W_sv2.D0_19-A3B.FM                          0.712095
Cr_pv6W_sv2.D0_19-A3B.NM                          0.712095
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM                0.584180
...                                                    ...
Cr_pv10W_sv3.mu-BAAAB.FM                          0.634381
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM                 0.584180
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM                 0.584180
Co_pv13W_sv16.chi-ABAB.NM                         0.565533
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM                0.584180

[1665 rows x 1 columns]

## Some extra info like magnetic configuration and know crystal structure

In [14]:
Features = Featurizer(BS)
BS['Mag'] = Features.Mag[BS.index].map(make_magnetic_feature)

In [15]:
CompositionFeatures = pd.concat([CompositionFeatures, Features.get_fractions_by_components()], axis =1 )

# Target quantities

In [31]:
groundstates=Features.get_ground_states_energies()
BS['EF'] = Features.get_formation_energy(ground_states_dic=groundstates)

# Some Machine learning

In [15]:
Params={'feature_selector__k': np.arange(10), 'regressor__max_depth': np.arange(20,30)}
model_selector = Pipeline(
    [
        ('feature_selector', SelectKBest()),
#        ('feature_selector', SequentialFeatureSelector(RandomForestRegressor())),
        ('regressor', RandomForestRegressor())
        
    ]
)

In [16]:
seqselector = SequentialFeatureSelector(RandomForestRegressor, n_features_to_select=10, n_jobs=3)

In [17]:
cv = GridSearchCV(model_selector, param_grid=Params,verbose=5, n_jobs=3,scoring='neg_root_mean_squared_error')

In [18]:
cv.fit(X_train, Y_train)

Fitting 5 folds for each of 100 candidates, totalling 500 fits

GridSearchCV(estimator=Pipeline(steps=[('feature_selector', SelectKBest()),
                                       ('regressor', RandomForestRegressor())]),
             n_jobs=3,
             param_grid={'feature_selector__k': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
                         'regressor__max_depth': array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])},
             scoring='neg_root_mean_squared_error', verbose=5)

In [19]:
cv.best_estimator_

Pipeline(steps=[('feature_selector', SelectKBest(k=9)),
                ('regressor', RandomForestRegressor(max_depth=28))])

In [20]:
AtomicFeatures.loc[:,cv.best_estimator_[0].get_support()].to_pickle('tables/BestAtomicFeatures.pkl')

In [20]:
AtomicFeatures.loc[:,cv.best_estimator_[0].get_support()].columns

Index(['MagpieData avg_dev NdUnfilled', 'MagpieData range NUnfilled',
       'MagpieData avg_dev NUnfilled', 'MagpieData range GSvolume_pa',
       'MagpieData avg_dev GSvolume_pa', 'MagpieData range GSmagmom',
       'MagpieData avg_dev GSmagmom', 'MagpieData range SpaceGroupNumber',
       'MagpieData avg_dev SpaceGroupNumber'],
      dtype='object')

In [27]:
#cv.cv_results_['mean_test_score'][
cv.best_estimator_[0].get_support()
#]

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False,  True, False,  True, False,
       False, False,  True, False,  True, False, False, False, False,
       False, False, False, False, False,  True, False,  True, False,
       False, False,  True, False,  True, False, False])

In [32]:
del FeatureConcatenate
FeatureConcatenate = SourceFileLoader('FeatureConcate','/home/storage/fortimtb/CuadernoTrabajo/bopfoxfeaturizer/BopFoxFeaturizer/FeatureConcatenate.py'
                                     ).load_module().FeatureConcatenate

param_grid = {} 
Bestfeatsatomic = {} 
Bestscoresatomic = {}
FC['RandomForest_atomic'] = FeatureConcatenate(
    pd.concat([AtomicFeaturesMagpie.loc[thissamples], BS[TARGET][thissamples]], axis=1), #DATA, 
    RandomForestRegressor(),
    model_params=param_grid,
    feature_list=AtomicFeaturesMagpie.columns,
    data_target=TARGET,
    criterion = criterion
#    sample_weights = w_train, #Classes['Weights']
)

Bestfeatsatomic['RandomForest_atomic'], Bestscoresatomic['RandomForest_atomic'] = FC['RandomForest_atomic'].build_features_list(
    best_feature_proposal=['MagConfig'],
    pass_force_refit=True,
    maxnumfeatures=15,
    report_prefix='RandomForest_atomic_'+CASE,
)

BestAtomic = pd.DataFrame(
    np.array([[x,y] for x,y in zip(Bestfeatsatomic['RandomForest_atomic'], Bestscoresatomic['RandomForest_atomic'])])
)

procesing '[]' with 'MagConfig' ... ::   0%|                                                      | 0/1 [00:00<?, ?it/s]

Refitting ..

procesing '[]' with 'MagConfig' ... :: 100%|##############################################| 1/1 [00:00<00:00,  1.42it/s]
procesing '['MagConfig']' with 'MagpieData avg_dev SpaceGroupNumber' ... ::   0%|               | 0/132 [00:00<?, ?it/s]

fitting has finished,  test_score  =  0.18844045061578052
Refitting ..

procesing '['MagConfig']' with 'MagpieData range Column' ... :: 100%|#################| 132/132 [01:42<00:00,  1.29it/s]

fitting has finished,  test_score  =  0.18412308189450954

procesing '['MagConfig', 'MagpieData mean Number']' with 'MagpieData avg_dev SpaceGroupNumber' ... ::   0%| | 0/83 [00:0

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number']' with 'MagpieData range Column' ... :: 100%|#| 83/83 [01:35<00:00,  1

fitting has finished,  test_score  =  0.12433571348948069

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData minimum AtomicWeight']' with 'MagpieData avg_dev SpaceGro

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData minimum AtomicWeight']' with 'MagpieData range Column' ..

fitting has finished,  test_score  =  0.12403074486274038

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData minimum AtomicWeight', 'MagpieData avg_dev MeltingT']' wi

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData minimum AtomicWeight', 'MagpieData avg_dev MeltingT']' wi

fitting has finished,  test_score  =  0.12441795556111446

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData minimum AtomicWeight', 'MagpieData avg_dev MeltingT', 'Ma

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData minimum AtomicWeight', 'MagpieData avg_dev MeltingT', 'Ma

fitting has finished,  test_score  =  0.12431590175726175

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData minimum AtomicWeight', 'MagpieData avg_dev MeltingT', 'Ma

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData minimum AtomicWeight', 'MagpieData avg_dev MeltingT', 'Ma

fitting has finished,  test_score  =  0.1249242998199052

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData minimum AtomicWeight', 'MagpieData avg_dev MeltingT', 'Ma

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData minimum AtomicWeight', 'MagpieData avg_dev MeltingT', 'Ma

fitting has finished,  test_score  =  0.12346745878736945

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData minimum AtomicWeight', 'MagpieData avg_dev MeltingT', 'Ma

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData minimum AtomicWeight', 'MagpieData avg_dev MeltingT', 'Ma

fitting has finished,  test_score  =  0.1238376689524037

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData minimum AtomicWeight', 'MagpieData avg_dev MeltingT', 'Ma

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData minimum AtomicWeight', 'MagpieData avg_dev MeltingT', 'Ma

fitting has finished,  test_score  =  0.12284475833268264

In [36]:
BestAtomic.to_csv(FileNames.get_table_filename('AtomicFeatures',''),index=None, header=None)

# Density Features

In [37]:
DensitiFeatures

                                      density        vpa  packing fraction
index
Co_pv6W_sv6.C14-BBA.FM              19.558247  10.305995               1.0
Co_pv6W_sv6.C14-BBA.NM              19.558247  10.305995               1.0
Cr_pv6W_sv2.D0_19-A3B.FM            12.599284  11.197029               1.0
Cr_pv6W_sv2.D0_19-A3B.NM            12.599284  11.197029               1.0
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM  14.703874  10.939619               1.0
...                                       ...        ...               ...
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM   13.109662  11.098025               1.0
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM   13.109662  11.098025               1.0
Co_pv13W_sv16.chi-ABAB.NM           20.599218  10.305995               1.0
Co_pv13W_sv16.chi-ABAB.FM           20.599218  10.305995               1.0
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM  14.703874  10.939619               1.0

[1687 rows x 3 columns]

# Composition Features

In [42]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [43]:
CompositionFeatures['MagConfig'] = Features.MagFeature

In [56]:
CompoFileNames = CaseNamer(CASE, 'CompositionalFeatures', '', '', criterion, '',)

In [44]:
CompositionFeatures.dropna(axis=1,inplace=True)

In [ ]:
CompoFileNames = CaseNamer()

In [45]:
CompositionFeatures

,HOMO_character,HOMO_element,HOMO_energy,LUMO_character,LUMO_element,LUMO_energy,gap_AO,band center,compound possible,max ionic char,avg ionic char,0-norm,2-norm,3-norm,5-norm,7-norm,10-norm,MagConfig
index,,,,,,,,,,,,,,,,,,
Co_pv6W_sv6.C14-BBA.FM,d,W,-0.220603,d,W,-0.220603,0.0,-2.311715,False,0.055973,0.004626,2,0.913625,0.909394,0.909093,0.909091,0.909091,2
Co_pv6W_sv6.C14-BBA.NM,d,W,-0.220603,d,W,-0.220603,0.0,-2.311715,False,0.055973,0.004626,2,0.913625,0.909394,0.909093,0.909091,0.909091,0
Cr_pv6W_sv2.D0_19-A3B.FM,d,W,-0.220603,d,W,-0.220603,0.0,-2.175953,False,0.115294,0.020466,2,0.803101,0.776092,0.769604,0.769255,0.769231,2
Cr_pv6W_sv2.D0_19-A3B.NM,d,W,-0.220603,d,W,-0.220603,0.0,-2.175953,False,0.115294,0.020466,2,0.803101,0.776092,0.769604,0.769255,0.769231,0
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM,s,Cr,-0.150445,s,Cr,-0.150445,0.0,-1.897795,False,0.115294,0.023840,3,0.642910,0.576008,0.543235,0.536132,0.533816,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM,d,Cr,-0.118123,d,Cr,-0.118123,0.0,-1.838481,False,0.115294,0.022026,3,0.721110,0.680809,0.668028,0.666823,0.666674,2
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM,d,Cr,-0.118123,d,Cr,-0.118123,0.0,-1.838481,False,0.115294,0.022026,3,0.721110,0.680809,0.668028,0.666823,0.666674,0
Co_pv13W_sv16.chi-ABAB.NM,d,W,-0.220603,d,W,-0.220603,0.0,-2.320017,False,0.055973,0.003890,2,0.927903,0.925021,0.924856,0.924855,0.924855,0
Co_pv13W_sv16.chi-ABAB.FM,d,W,-0.220603,d,W,-0.220603,0.0,-2.320017,False,0.055973,0.003890,2,0.927903,0.925021,0.924856,0.924855,0.924855,2
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM,s,Cr,-0.150445,s,Cr,-0.150445,0.0,-1.897795,False,0.115294,0.023840,3,0.642910,0.576008,0.543235,0.536132,0.533816,0

In [46]:
text_columns = CompositionFeatures.select_dtypes(include=['object']).columns

In [47]:
float_columns = CompositionFeatures.select_dtypes(include=['float']).columns

In [48]:
from sklearn.pipeline import Pipeline

In [50]:
OHE = OneHotEncoder(sparse=True)

In [51]:
OHE.fit_transform(CompositionFeatures[text_columns])

<1687x10 sparse matrix of type '<class 'numpy.float64'>'
	with 6748 stored elements in Compressed Sparse Row format>

In [52]:
del FeatureConcatenate
FeatureConcatenate = SourceFileLoader('FeatureConcate','/home/storage/fortimtb/CuadernoTrabajo/bopfoxfeaturizer/BopFoxFeaturizer/FeatureConcatenate.py'
                                     ).load_module().FeatureConcatenate

param_grid = {} 
Bestfeatsatomic = {} 
Bestscoresatomic = {}
FC['RandomForest_atomic'] = FeatureConcatenate(
    pd.concat([AtomicFeaturesMagpie.loc[thissamples], BS[TARGET][thissamples]], axis=1), #DATA, 
    RandomForestRegressor(),
    model_params=param_grid,
    feature_list=AtomicFeaturesMagpie.columns,
    data_target=TARGET,
    criterion = criterion
#    sample_weights = w_train, #Classes['Weights']
)

Bestfeatsatomic['RandomForest_atomic'], Bestscoresatomic['RandomForest_atomic'] = FC['RandomForest_atomic'].build_features_list(
    best_feature_proposal=['MagConfig'],
    pass_force_refit=True,
    report_prefix='RandomForest_atomic_'+CASE,
)

BestAtomic = pd.DataFrame(
    np.array([[x,y] for x,y in zip(Bestfeatsatomic['RandomForest_atomic'], Bestscoresatomic['RandomForest_atomic'])])
)

procesing '[]' with 'MagConfig' ... ::   0%|                                                      | 0/1 [00:00<?, ?it/s]

Refitting ..

procesing '[]' with 'MagConfig' ... :: 100%|##############################################| 1/1 [00:00<00:00,  1.45it/s]
procesing '['MagConfig']' with 'MagpieData avg_dev SpaceGroupNumber' ... ::   0%|               | 0/132 [00:00<?, ?it/s]

fitting has finished,  test_score  =  0.18841809340210108
Refitting ..

procesing '['MagConfig']' with 'MagpieData range Column' ... :: 100%|#################| 132/132 [01:42<00:00,  1.29it/s]

fitting has finished,  test_score  =  0.18485570444491098

procesing '['MagConfig', 'MagpieData mean Number']' with 'MagpieData avg_dev SpaceGroupNumber' ... ::   0%| | 0/83 [00:0

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number']' with 'MagpieData range Column' ... :: 100%|#| 83/83 [01:34<00:00,  1

fitting has finished,  test_score  =  0.12476534847072361

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData range MendeleevNumber']' with 'MagpieData mode NsUnfilled

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData range MendeleevNumber']' with 'MagpieData mean NdValence'

fitting has finished,  test_score  =  0.12343523729141323

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData range MendeleevNumber', 'MagpieData maximum NsValence']'

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData range MendeleevNumber', 'MagpieData maximum NsValence']'

fitting has finished,  test_score  =  0.12450935437591966

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData range MendeleevNumber', 'MagpieData maximum NsValence', '

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData range MendeleevNumber', 'MagpieData maximum NsValence', '

fitting has finished,  test_score  =  0.12357809436240608

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData range MendeleevNumber', 'MagpieData maximum NsValence', '

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData range MendeleevNumber', 'MagpieData maximum NsValence', '

fitting has finished,  test_score  =  0.12399957995502849

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData range MendeleevNumber', 'MagpieData maximum NsValence', '

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData range MendeleevNumber', 'MagpieData maximum NsValence', '

fitting has finished,  test_score  =  0.1249571514024632

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData range MendeleevNumber', 'MagpieData maximum NsValence', '

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData range MendeleevNumber', 'MagpieData maximum NsValence', '

fitting has finished,  test_score  =  0.12340525040789804

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData range MendeleevNumber', 'MagpieData maximum NsValence', '

Refitting ..

procesing '['MagConfig', 'MagpieData mean Number', 'MagpieData range MendeleevNumber', 'MagpieData maximum NsValence', '

fitting has finished,  test_score  =  0.12432811585287593

NameError: name 'get_table_filename' is not defined

In [53]:
BestAtomic

                                  0                    1
0                         MagConfig  0.18841809340210108
1            MagpieData mean Number  0.12487268873505242
2  MagpieData range MendeleevNumber  0.12279246649939976
3      MagpieData maximum NsValence   0.1223641182591462
4   MagpieData minimum AtomicWeight  0.12299821656019043
5         MagpieData mode GSbandgap  0.12269944904419666
6      MagpieData minimum NdValence  0.12269088063832162
7            MagpieData avg_dev Row  0.12309670717528305
8        MagpieData mode NpUnfilled  0.12296352884887714
9        MagpieData range GSbandgap  0.12288964971148236

In [57]:
BestAtomic.to_csv(CompoFileNames.get_table_filename('CompoFeatures',FC['RandomForest_atomic'].criterion))

In [58]:
who

AGNIFingerprints	 AtomicFeatures	 AtomicFeaturesMagpie	 AtomicOrbitals	 AtomicPackingEfficiency	 BS	 BandCenter	 BestAtomic	 Bestfeatsatomic
Bestscoresatomic	 BopfoxFeatures	 CASE	 CUTOFF	 CaseNamer	 ChemEnvSiteFingerprint	 ChemicalOrdering	 CompoFileNames	 CompositionFeatures
CompositionToOxidComposition	 CrystalNNFingerprint	 DensitiFeatures	 DensityFeatures	 DictToObject	 ElectronAffinity	 ElectronegativityDiff	 ElectronicRadialDistributionFunction	 ElementProperty
FC	 FeatureConcatenate	 Features	 Featurizer	 FileNames	 GridSearchCV	 HF	 IonProperty	 LabelEncoder
MODEL	 MaximumPackingEfficiency	 MultipleFeaturizer	 OHE	 OneHotEncoder	 OxidationStates	 Params	 Pipeline	 Plotting
RadialDistributionFunction	 RandomForestRegressor	 SOAP	 SelectKBest	 SequentialFeatureSelector	 SiteStatsFingerprint	 SourceFileLoader	 Stoichiometry	 StrToComposition
StructSummaryParser	 StructuralHeterogeneity	 StructureComposition	 StructureFeatures	 TARGET	 TMetalFraction	 ValenceOrbital	 VoronoiFingerprint	 X_test
X_train	 Y_test	 Y_train	 bestfeats	 bestscores	 case	 criterion	 cutoffs_dict	 cv
float_columns	 get_chemical_formula	 groundstates	 load_atomic_features	 load_composition_features	 load_density_features	 load_features	 load_radial_distriutions	 load_soap_features
load_structure_features	 make_magnetic_feature	 mean_squared_error	 mmfcomposition	 mmfdensity	 mmflatomic	 mmfstructure	 mmsoapfeatures	 model_selector
need_to_update	 np	 os	 param_grid	 pd	 pdb	 pi	 pickle	 plt
px	 run_list_of_featurizers	 seqselector	 struct_db	 sys	 text_columns	 thissamples	 tqdm	 train_test_split

# Structure Features

In [60]:
DensityFeatures

matminer.featurizers.structure.DensityFeatures

In [61]:
from mendeleev import element

In [65]:
W =element('W')

In [70]:
element('Co').

116.0