#  Calculation of features from available libraries

- input curated BS

# TODO: 
- MUST: include SOAP ! SOAP from matminer and dscribe wont work, apparently. retunrs None!
- try pyscal descriptors

In [19]:
import sys
sys.path.insert(0, '/home/storage/fortimtb/CuadernoTrabajo/bopfoxfeaturizer/')

dataset = 'Cr-Co-W'
from BopFoxFeaturizer.Featurizer import Featurizer
from Tools.DatasetTools.GetPymatgenFeatures import *

mmflatomic = os.path.join(dataset,'matminer_atomic_features.pkl')
mmfdensity = os.path.join (dataset, 'matminer_density_features.pkl')
mmfcomposition =  os.path.join (dataset,'matminer_composition_features.pkl')
mmfstructure =  os.path.join (dataset,'matminer_structure_features.pkl')
mmsoapfeatures = os.path.join(dataset, 'matminer_soap_features.pkl')

BS = pd.read_pickle(os.path.join(dataset, 'CuratedParsedBriefSummary.pkl'))
AtomsObjects = pd.read_pickle(os.path.join(dataset, 'CrCoW-sorted-POSCAR-initial-rescaled-PymatgenStructures.pkl')).dropna()
BS['atoms_objects'] = AtomsObjects.dropna()
BS.dropna(inplace=True)

BS['chemical_formula'] = get_chemical_formula(BS)

# Matminer Features

In [2]:
BS['composition'] = StrToComposition().featurize_dataframe(BS, "chemical_formula")['composition']

StrToComposition:   0%|          | 0/1682 [00:00<?, ?it/s]

In [3]:
AtomicFeaturesMagpie = load_features(mmflatomic, BS, which='atomic')
DensitiFeatures= load_features(mmfdensity, BS, which='density')
CompositionFeatures = load_features(mmfcomposition, BS, which='composition')
SOAPFeatures = load_features(mmfstructure, BS, which='soap')
# SOAP doesnt work from matminer

In [4]:
StructureFeatures = load_features(mmfstructure, BS, which='structure')

In [5]:
StructureFeatures.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [Co_pv6W_sv6.C14-BBA.FM, Co_pv6W_sv6.C14-BBA.NM, Cr_pv6W_sv2.D0_19-A3B.FM, Cr_pv6W_sv2.D0_19-A3B.NM, Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM, Co_pv10W_sv14.C36-BABBA.NM, Cr_pv2Co_pv12W_sv16.sigma-ABBCC.NM, Cr_pv7Co_pv2W_sv4.mu-AACBC.FM, Cr_pv7Co_pv2W_sv4.mu-AACBC.NM, Cr_pv2Co_pv4W_sv7.mu-CCBAB.NM, Cr_pv2Co_pv4W_sv7.mu-CCBAB.FM, Cr_pv1Co_pv6W_sv6.mu-ABCCC.FM, Cr_pv1Co_pv6W_sv6.mu-ABCCC.NM, Cr_pv2Co_pv12W_sv16.sigma-ABBCC.FM, Cr_pv10Co_pv8W_sv12.sigma-ACCAB.NM, Cr_pv10Co_pv6W_sv8.C36-CCABA.FM, Cr_pv10Co_pv6W_sv8.C36-CCABA.NM, Cr_pv10Co_pv8W_sv12.sigma-ACCAB.FM, Cr_pv2Co_pv12W_sv16.sigma-ABCCB.FM, Cr_pv2Co_pv12W_sv16.sigma-ABCCB.NM, Co_pv5W_sv8.mu-ABAAB.NM, Co_pv14W_sv16.sigma-AABAB.NM, Co_pv10W_sv14.C36-BABBA.FM, Cr_pv24W_sv6.sigma-BBAAA.FM, Cr_pv24W_sv6.sigma-BBAAA.NM, Cr_pv13Co_pv4W_sv12.chi-ABAC.NM, Cr_pv13Co_pv4W_sv12.chi-ABAC.FM, Co_pv14W_sv16.sigma-AABAB.FM, Cr_pv20Co_pv2W_sv8.sigma-BAAAC.NM, Cr_pv20Co_pv2W_sv8.sigma-BAAAC.FM, Cr_pv10Co_pv6W_sv8.C36-CCAAB.NM, Cr_pv10Co_pv6W_sv8.C36-CCAAB.FM, Cr_pv10Co_pv8W_sv12.sigma-ACBAC.NM, Cr_pv10Co_pv8W_sv12.sigma-ACBAC.FM, Co_pv10W_sv14.C36-ABBBA.NM, Co_pv10W_sv14.C36-ABBBA.FM, Co_pv5W_sv8.mu-ABAAB.FM, Cr_pv10W_sv3.mu-BABAA.NM, Cr_pv10W_sv3.mu-BABAA.FM, Cr_pv10Co_pv8W_sv12.sigma-ACBCA.FM, Cr_pv10Co_pv8W_sv12.sigma-ACBCA.NM, Cr_pv5Co_pv2W_sv6.mu-ACBAA.NM, Cr_pv5Co_pv2W_sv6.mu-ACBAA.FM, Co_pv13W_sv16.chi-ABBA.NM, Cr_pv5Co_pv2W_sv6.mu-ACABA.FM, Cr_pv5Co_pv2W_sv6.mu-ACABA.NM, Cr_pv1Co_pv12W_sv16.chi-ACBC.NM, Cr_pv1Co_pv12W_sv16.chi-ACBC.FM, Cr_pv10W_sv3.mu-BAABA.FM, Cr_pv10W_sv3.mu-BAABA.NM, Cr_pv7Co_pv2W_sv4.mu-AACCB.NM, Cr_pv7Co_pv2W_sv4.mu-AACCB.FM, Cr_pv10Co_pv4W_sv10.C36-BCAAC.NM, Cr_pv10Co_pv4W_sv10.C36-BCAAC.FM, Co_pv13W_sv16.chi-ABBA.FM, Cr_pv16Co_pv4W_sv10.sigma-CBCAA.NM, Cr_pv16Co_pv4W_sv10.sigma-CBCAA.FM, Cr_pv10Co_pv8W_sv12.sigma-ACABC.NM, Cr_pv10Co_pv8W_sv12.sigma-ACABC.FM, Cr_pv10Co_pv4W_sv10.C36-BCACA.NM, Cr_pv10Co_pv4W_sv10.C36-BCACA.FM, Cr_pv20Co_pv2W_sv8.sigma-BACAA.FM, Cr_pv20Co_pv2W_sv8.sigma-BACAA.NM, Cr_pv10Co_pv4W_sv10.C36-CBACA.NM, Cr_pv10Co_pv4W_sv10.C36-CBACA.FM, Cr_pv22W_sv8.sigma-AAABA.FM, Cr_pv22W_sv8.sigma-AAABA.NM, Co_pv4W_sv8.C14-ABB.NM, Cr_pv10Co_pv4W_sv10.C36-ACBAC.FM, Cr_pv10Co_pv4W_sv10.C36-ACBAC.NM, Cr_pv8Co_pv4W_sv12.C36-BAACC.NM, Cr_pv5Co_pv2W_sv6.mu-ACAAB.FM, Cr_pv5Co_pv2W_sv6.mu-ACAAB.NM, Co_pv8W_sv16.C36-AABBB.NM, Cr_pv10Co_pv4W_sv10.C36-CBAAC.NM, Cr_pv10Co_pv4W_sv10.C36-CBAAC.FM, Cr_pv10Co_pv4W_sv10.C36-CABAC.NM, Cr_pv10Co_pv4W_sv10.C36-CABAC.FM, Cr_pv10Co_pv4W_sv10.C36-CABCA.FM, Cr_pv10Co_pv4W_sv10.C36-CABCA.NM, Cr_pv10Co_pv8W_sv12.sigma-ACCBA.NM, Cr_pv10Co_pv8W_sv12.sigma-ACCBA.FM, Co_pv2W_sv4.C15-AB2.NM, Cr_pv8Co_pv8W_sv14.sigma-CCACB.NM, Cr_pv8Co_pv8W_sv14.sigma-CCACB.FM, Cr_pv10Co_pv4W_sv10.C36-ACBCA.FM, Cr_pv10Co_pv4W_sv10.C36-ACBCA.NM, Cr_pv8Co_pv4W_sv12.C36-ABACC.NM, Cr_pv12Co_pv5W_sv12.chi-BBCA.NM, Cr_pv12Co_pv5W_sv12.chi-BBCA.FM, Cr_pv8Co_pv4W_sv12.C36-BAACC.FM, Cr_pv1Co_pv12W_sv16.chi-ACCB.FM, Cr_pv1Co_pv12W_sv16.chi-ACCB.NM, Cr_pv1Co_pv4W_sv8.mu-ACBBC.FM, Cr_pv1Co_pv4W_sv8.mu-ACBBC.NM, Cr_pv6Co_pv2W_sv5.mu-CABCC.NM, Cr_pv6Co_pv2W_sv5.mu-CABCC.FM, Cr_pv8Co_pv4W_sv12.C36-ABACC.FM, Cr_pv6W_sv2.A15-AB.FM, Cr_pv6W_sv2.A15-AB.NM, ...]

[1682 rows x 0 columns]

In [6]:
AtomicFeaturesMagpie.columns = AtomicFeaturesMagpie.columns.str.replace('MagpieData ','')

In [7]:
AtomicFeaturesMagpie.dropna(axis=1, inplace = True)

In [8]:
AtomicFeaturesMagpie.describe()

,minimum Number,maximum Number,range Number,mean Number,avg_dev Number,mode Number,minimum MendeleevNumber,maximum MendeleevNumber,range MendeleevNumber,mean MendeleevNumber,...,range GSmagmom,mean GSmagmom,avg_dev GSmagmom,mode GSmagmom,minimum SpaceGroupNumber,maximum SpaceGroupNumber,range SpaceGroupNumber,mean SpaceGroupNumber,avg_dev SpaceGroupNumber,mode SpaceGroupNumber
count,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,...,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000
mean,24.889417,67.341855,42.452438,46.688676,13.380331,47.074316,49.365636,56.844233,7.478597,52.764686,...,1.282414,0.498221,0.420355,0.465830,199.659929,228.646254,28.986326,217.738752,9.501260,217.159929
std,4.924017,16.448294,16.905425,15.834961,8.460133,24.012882,1.111332,2.640596,2.761998,2.126883,...,0.584293,0.444882,0.277937,0.710371,12.890365,3.501892,13.206741,10.055647,6.282187,16.564369
min,24.000000,24.000000,0.000000,24.000000,0.000000,24.000000,49.000000,49.000000,0.000000,49.000000,...,0.000000,0.000000,0.000000,0.000000,194.000000,194.000000,0.000000,194.000000,0.000000,194.000000
25%,24.000000,74.000000,47.000000,33.307692,5.848889,27.000000,49.000000,58.000000,7.000000,51.068966,...,1.548471,0.119113,0.181461,0.000000,194.000000,229.000000,35.000000,212.666667,4.101562,194.000000
50%,24.000000,74.000000,50.000000,44.615385,13.569692,27.000000,49.000000,58.000000,9.000000,52.125000,...,1.548471,0.387118,0.430131,0.000000,194.000000,229.000000,35.000000,220.250000,9.722222,229.000000
75%,24.000000,74.000000,50.000000,62.461538,21.555556,74.000000,49.000000,58.000000,9.000000,53.854885,...,1.548471,0.722620,0.688209,1.548471,194.000000,229.000000,35.000000,226.307692,15.555556,229.000000
max,74.000000,74.000000,50.000000,74.000000,24.793388,74.000000,58.000000,58.000000,9.000000,58.000000,...,1.548471,1.548471,0.774236,1.548471,229.000000,229.000000,35.000000,229.000000,17.500000,229.000000

In [9]:
DensitiFeatures.dropna(axis=1, inplace=True)

In [10]:
DensitiFeatures.describe()

           density          vpa  packing fraction
count  1682.000000  1682.000000       1682.000000
mean     15.310397    10.707217          0.999421
std       5.095531     0.355799          0.023764
min       0.649612     2.576499          0.025403
25%      11.429203    10.488771          1.000000
50%      14.675017    10.702010          1.000000
75%      18.815359    10.939619          1.000000
max      29.620964    11.494040          1.000000

In [11]:
CompositionFeatures.dropna(axis=1, inplace=True)

In [12]:
CompositionFeatures.describe()

,HOMO_energy,LUMO_energy,gap_AO,band center,max ionic char,avg ionic char,0-norm,2-norm,3-norm,5-norm,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
count,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,...,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000,1682.000000
mean,-0.207638,-0.206620,0.001018,4.184175,0.091799,0.012611,2.549941,0.755381,0.713485,0.693308,...,1.282414,0.498221,0.420355,0.465830,199.659929,228.646254,28.986326,217.738752,9.501260,217.159929
std,0.050235,0.051077,0.005899,0.148919,0.039820,0.008055,0.557414,0.138233,0.169465,0.187588,...,0.584293,0.444882,0.277937,0.710371,12.890365,3.501892,13.206741,10.055647,6.282187,16.564369
min,-0.322368,-0.322368,0.000000,3.716833,0.000000,0.000000,1.000000,0.584998,0.493242,0.435713,...,0.000000,0.000000,0.000000,0.000000,194.000000,194.000000,0.000000,194.000000,0.000000,194.000000
25%,-0.220603,-0.220603,0.000000,4.080115,0.055973,0.004755,2.000000,0.628932,0.563224,0.530175,...,1.548471,0.119113,0.181461,0.000000,194.000000,229.000000,35.000000,212.666667,4.101562,194.000000
50%,-0.220603,-0.220603,0.000000,4.199398,0.115294,0.013709,3.000000,0.707107,0.673540,0.651528,...,1.548471,0.387118,0.430131,0.000000,194.000000,229.000000,35.000000,220.250000,9.722222,229.000000
75%,-0.181413,-0.181413,0.000000,4.298091,0.115294,0.019364,3.000000,0.897130,0.890964,0.890416,...,1.548471,0.722620,0.688209,1.548471,194.000000,229.000000,35.000000,226.307692,15.555556,229.000000
max,-0.118123,-0.118123,0.054052,4.397803,0.115294,0.028585,3.000000,1.000000,1.000000,1.000000,...,1.548471,1.548471,0.774236,1.548471,229.000000,229.000000,35.000000,229.000000,17.500000,229.000000

In [13]:
SOAPFeatures.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [Co_pv6W_sv6.C14-BBA.FM, Co_pv6W_sv6.C14-BBA.NM, Cr_pv6W_sv2.D0_19-A3B.FM, Cr_pv6W_sv2.D0_19-A3B.NM, Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM, Co_pv10W_sv14.C36-BABBA.NM, Cr_pv2Co_pv12W_sv16.sigma-ABBCC.NM, Cr_pv7Co_pv2W_sv4.mu-AACBC.FM, Cr_pv7Co_pv2W_sv4.mu-AACBC.NM, Cr_pv2Co_pv4W_sv7.mu-CCBAB.NM, Cr_pv2Co_pv4W_sv7.mu-CCBAB.FM, Cr_pv1Co_pv6W_sv6.mu-ABCCC.FM, Cr_pv1Co_pv6W_sv6.mu-ABCCC.NM, Cr_pv2Co_pv12W_sv16.sigma-ABBCC.FM, Cr_pv10Co_pv8W_sv12.sigma-ACCAB.NM, Cr_pv10Co_pv6W_sv8.C36-CCABA.FM, Cr_pv10Co_pv6W_sv8.C36-CCABA.NM, Cr_pv10Co_pv8W_sv12.sigma-ACCAB.FM, Cr_pv2Co_pv12W_sv16.sigma-ABCCB.FM, Cr_pv2Co_pv12W_sv16.sigma-ABCCB.NM, Co_pv5W_sv8.mu-ABAAB.NM, Co_pv14W_sv16.sigma-AABAB.NM, Co_pv10W_sv14.C36-BABBA.FM, Cr_pv24W_sv6.sigma-BBAAA.FM, Cr_pv24W_sv6.sigma-BBAAA.NM, Cr_pv13Co_pv4W_sv12.chi-ABAC.NM, Cr_pv13Co_pv4W_sv12.chi-ABAC.FM, Co_pv14W_sv16.sigma-AABAB.FM, Cr_pv20Co_pv2W_sv8.sigma-BAAAC.NM, Cr_pv20Co_pv2W_sv8.sigma-BAAAC.FM, Cr_pv10Co_pv6W_sv8.C36-CCAAB.NM, Cr_pv10Co_pv6W_sv8.C36-CCAAB.FM, Cr_pv10Co_pv8W_sv12.sigma-ACBAC.NM, Cr_pv10Co_pv8W_sv12.sigma-ACBAC.FM, Co_pv10W_sv14.C36-ABBBA.NM, Co_pv10W_sv14.C36-ABBBA.FM, Co_pv5W_sv8.mu-ABAAB.FM, Cr_pv10W_sv3.mu-BABAA.NM, Cr_pv10W_sv3.mu-BABAA.FM, Cr_pv10Co_pv8W_sv12.sigma-ACBCA.FM, Cr_pv10Co_pv8W_sv12.sigma-ACBCA.NM, Cr_pv5Co_pv2W_sv6.mu-ACBAA.NM, Cr_pv5Co_pv2W_sv6.mu-ACBAA.FM, Co_pv13W_sv16.chi-ABBA.NM, Cr_pv5Co_pv2W_sv6.mu-ACABA.FM, Cr_pv5Co_pv2W_sv6.mu-ACABA.NM, Cr_pv1Co_pv12W_sv16.chi-ACBC.NM, Cr_pv1Co_pv12W_sv16.chi-ACBC.FM, Cr_pv10W_sv3.mu-BAABA.FM, Cr_pv10W_sv3.mu-BAABA.NM, Cr_pv7Co_pv2W_sv4.mu-AACCB.NM, Cr_pv7Co_pv2W_sv4.mu-AACCB.FM, Cr_pv10Co_pv4W_sv10.C36-BCAAC.NM, Cr_pv10Co_pv4W_sv10.C36-BCAAC.FM, Co_pv13W_sv16.chi-ABBA.FM, Cr_pv16Co_pv4W_sv10.sigma-CBCAA.NM, Cr_pv16Co_pv4W_sv10.sigma-CBCAA.FM, Cr_pv10Co_pv8W_sv12.sigma-ACABC.NM, Cr_pv10Co_pv8W_sv12.sigma-ACABC.FM, Cr_pv10Co_pv4W_sv10.C36-BCACA.NM, Cr_pv10Co_pv4W_sv10.C36-BCACA.FM, Cr_pv20Co_pv2W_sv8.sigma-BACAA.FM, Cr_pv20Co_pv2W_sv8.sigma-BACAA.NM, Cr_pv10Co_pv4W_sv10.C36-CBACA.NM, Cr_pv10Co_pv4W_sv10.C36-CBACA.FM, Cr_pv22W_sv8.sigma-AAABA.FM, Cr_pv22W_sv8.sigma-AAABA.NM, Co_pv4W_sv8.C14-ABB.NM, Cr_pv10Co_pv4W_sv10.C36-ACBAC.FM, Cr_pv10Co_pv4W_sv10.C36-ACBAC.NM, Cr_pv8Co_pv4W_sv12.C36-BAACC.NM, Cr_pv5Co_pv2W_sv6.mu-ACAAB.FM, Cr_pv5Co_pv2W_sv6.mu-ACAAB.NM, Co_pv8W_sv16.C36-AABBB.NM, Cr_pv10Co_pv4W_sv10.C36-CBAAC.NM, Cr_pv10Co_pv4W_sv10.C36-CBAAC.FM, Cr_pv10Co_pv4W_sv10.C36-CABAC.NM, Cr_pv10Co_pv4W_sv10.C36-CABAC.FM, Cr_pv10Co_pv4W_sv10.C36-CABCA.FM, Cr_pv10Co_pv4W_sv10.C36-CABCA.NM, Cr_pv10Co_pv8W_sv12.sigma-ACCBA.NM, Cr_pv10Co_pv8W_sv12.sigma-ACCBA.FM, Co_pv2W_sv4.C15-AB2.NM, Cr_pv8Co_pv8W_sv14.sigma-CCACB.NM, Cr_pv8Co_pv8W_sv14.sigma-CCACB.FM, Cr_pv10Co_pv4W_sv10.C36-ACBCA.FM, Cr_pv10Co_pv4W_sv10.C36-ACBCA.NM, Cr_pv8Co_pv4W_sv12.C36-ABACC.NM, Cr_pv12Co_pv5W_sv12.chi-BBCA.NM, Cr_pv12Co_pv5W_sv12.chi-BBCA.FM, Cr_pv8Co_pv4W_sv12.C36-BAACC.FM, Cr_pv1Co_pv12W_sv16.chi-ACCB.FM, Cr_pv1Co_pv12W_sv16.chi-ACCB.NM, Cr_pv1Co_pv4W_sv8.mu-ACBBC.FM, Cr_pv1Co_pv4W_sv8.mu-ACBBC.NM, Cr_pv6Co_pv2W_sv5.mu-CABCC.NM, Cr_pv6Co_pv2W_sv5.mu-CABCC.FM, Cr_pv8Co_pv4W_sv12.C36-ABACC.FM, Cr_pv6W_sv2.A15-AB.FM, Cr_pv6W_sv2.A15-AB.NM, ...]

[1682 rows x 0 columns]

## Some extra info like magnetic configuration and know crystal structure

In [14]:
Features = Featurizer(BS)
BS['Mag'] = Features.Mag[BS.index].map(make_magnetic_feature)

In [15]:
CompositionFeatures = pd.concat([CompositionFeatures, Features.get_fractions_by_components()], axis =1 )

# Pyscal features

In [1]:
import pyscal as pc
import pandas as pd
from tqdm.auto import tqdm
import numpy as np
import multiprocessing as mp
from tqdm.notebook import tqdm_notebook
tqdm_notebook.pandas()

AtomsObjects = pd.read_pickle('Cr-Co-W/CrCoW-sorted-POSCAR-initial-rescaled-AtomsObjects.pkl').dropna()

from pyscalfeaturizers import *

In [2]:
AtomsObjects = pd.read_pickle('Cr-Co-W/CrCoW-sorted-POSCAR-initial-rescaled-AtomsObjects.pkl').dropna()
featurizers = [pyscal_steinhardt, pyscal_cn] #, get_steinhardt]
Features = featurize_many(AtomsObjects,  featurizers, colid='atoms')
#with open('pyscal_features.kpl','wb') as pkl:
#    pickle.dump(Features, pkl)

pyscal_steinhardt

  0%|          | 0/1682 [00:00<?, ?it/s]

pyscal_cn

  0%|          | 0/1682 [00:00<?, ?it/s]

In [5]:
Features = results

In [37]:
Features['pyscal_cn'] = Features['pyscal_cn'].apply(np.array)

## Averaging

In [38]:
neighbours  = {'CN12': 12, 'CN14': 14, 'CN15': 15, 'CN16': 16}

In [39]:
q4, q6  = np.array([thisq for thisq in Features['pyscal_steinhardt'][0]])

In [48]:
cn = Features['pyscal_cn'][0]

In [54]:
cn

array([16, 16, 16, 16, 12, 12, 12, 12, 12, 12, 12, 12])

In [56]:
average = {}
for tcp, tcn in neighbours.items():
    print(tcp, tcn)
    average.update({tcp: q4[cn==tcn].sum()/len(q4)})

CN12 12
CN14 14
CN15 15
CN16 16

In [57]:
average

{'CN12': 0.020734710875966064,
 'CN14': 0.0,
 'CN15': 0.0,
 'CN16': 0.0010193559601119056}