# Prepare the features

- BOP features arrangement and averagings
- Library Features arrangement ad averaging
- Matminer features cleanup (decide min, max or avg)
- clear feature list from correlations
- outlier detection based on features
- Feature Distribution plots

 - input : features dataframes from prev steps
 - output: clean features dataframes into picles

In [1]:
import pandas as pd
import seaborn
import matplotlib.pyplot as plt
import copy
import os
import numpy as np
import pdb
from tqdm.auto import tqdm 
from Tools.DatasetTools import GeneralFeaturizer as gf
dataset = 'Cr-Co-W/'
descriptorlocation = os.path.join(dataset, 'Descriptors')

In [52]:
import pdb

# Load Features

In [2]:
PyscalFeaturesFile = os.path.join(descriptorlocation, 'pyscal_steinhardt.kpl')
BopFeaturesFile = os.path.join(descriptorlocation, 'CrCoW_initial_canonical_table_WUBIND_16.pkl')
AtomicFeaturesFile = os.path.join(descriptorlocation, 'matminer_atomic_features.pkl')
CompositionFeaturesFile = os.path.join(descriptorlocation, 'matminer_composition_features.pkl')

PyscalFeatures = pd.read_pickle(PyscalFeaturesFile)
BopFeatures = pd.read_pickle(BopFeaturesFile)
AtomicFeatures = pd.read_pickle(AtomicFeaturesFile)
CompositionFeatures = pd.read_pickle(CompositionFeaturesFile)

## Averaging Pyscal Features

In [3]:
gf.cn_average((PyscalFeatures.index[0], PyscalFeatures.pyscal_steinhardt.iloc[0]), ('', PyscalFeatures.pyscal_cn.iloc[0]))

{'Co_pv6W_sv6.C14-BBA.FM': {'0_CN12': 0.12440826525579637,
  '0_CN14': 0.0,
  '0_CN15': 0.0,
  '0_CN16': 0.006116135760671434,
  '1_CN12': 2.6167554193863327,
  '1_CN14': 0.0,
  '1_CN15': 0.0,
  '1_CN16': 0.3867610747010618}}

In [4]:
PyscalFeaturesAveraged = gf.cnaverage_dataframe(PyscalFeatures, ['pyscal_steinhardt'], PyscalFeatures.pyscal_cn)

cnaverage pyscal_steinhardt

  0%|          | 0/1682 [00:00<?, ?it/s]

In [5]:
columns = PyscalFeaturesAveraged['pyscal_steinhardt'].columns

In [6]:
NamedFeatures = [ f'pyscal_steinhardt_{column}' for column in columns ]

In [7]:
PyscalFeaturesAveraged['pyscal_steinhardt'].columns = NamedFeatures

In [8]:
PyscalFeaturesAveraged['pyscal_steinhardt']

,pyscal_steinhardt_0_CN12,pyscal_steinhardt_0_CN14,pyscal_steinhardt_0_CN15,pyscal_steinhardt_0_CN16,pyscal_steinhardt_1_CN12,pyscal_steinhardt_1_CN14,pyscal_steinhardt_1_CN15,pyscal_steinhardt_1_CN16
Co_pv6W_sv6.C14-BBA.FM,0.124408,0.000000,0.000000,0.006116,2.616755,0.000000,0.000000,0.386761
Co_pv6W_sv6.C14-BBA.NM,0.124408,0.000000,0.000000,0.006116,2.616755,0.000000,0.000000,0.386761
Cr_pv6W_sv2.D0_19-A3B.FM,0.358571,0.000000,0.000000,0.000000,1.928079,0.000000,0.000000,0.000000
Cr_pv6W_sv2.D0_19-A3B.NM,0.358571,0.000000,0.000000,0.000000,1.928079,0.000000,0.000000,0.000000
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM,0.569610,0.333508,0.046279,0.000000,3.138225,3.265551,0.631690,0.000000
...,...,...,...,...,...,...,...,...
Cr_pv10W_sv3.mu-BAAAB.FM,0.237079,0.029578,0.001613,0.014745,2.215254,0.398773,0.293269,0.203913
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM,0.569610,0.333508,0.046279,0.000000,3.138225,3.265551,0.631690,0.000000
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM,0.569610,0.333508,0.046279,0.000000,3.138225,3.265551,0.631690,0.000000
Co_pv13W_sv16.chi-ABAB.NM,0.000000,0.000000,0.000000,0.074691,0.000000,0.000000,0.000000,0.490910
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM,0.569610,0.333508,0.046279,0.000000,3.138225,3.265551,0.631690,0.000000

In [9]:
PyscalFeaturesAveraged['pyscal_steinhardt'].to_pickle(os.path.join(descriptorlocation,'PyscalFeaturesAveraged.pkl'))

# Arrangement and averaging BOP Features

In [10]:
BopFeatures

,U_bind,U_bond_atom,U_bond_atom_list,moments,normed_moments,an,bn,sigma,Ainf,Binf
Co_pv6W_sv6.C14-BBA.FM,-58.644616,-78.588438,"[-4.3975143698, -4.3975143698, -4.3975143698, ...","[[0.0, 1.30409, -0.634205, 4.08953, -4.29737, ...","[[0.0717862986, 0.0843546428, 0.0079343959, 0....","[[0.0, -0.48632200000000003, -0.22576999999999...","[[0.0, 1.14197, 1.26307, 1.51045, 1.71511, 1.7...","[[1.0, 0.143370955, -0.6601173127, -0.22212161...","[-0.2912918773, -0.2912918773, -0.2912918773, ...","[2.0288821321, 2.0288821321, 2.0288821321, 2.0..."
Co_pv6W_sv6.C14-BBA.NM,-58.644616,-78.588438,"[-4.3975143698, -4.3975143698, -4.3975143698, ...","[[0.0, 1.30409, -0.634205, 4.08953, -4.29737, ...","[[0.0717862986, 0.0843546428, 0.0079343959, 0....","[[0.0, -0.48632200000000003, -0.22576999999999...","[[0.0, 1.14197, 1.26307, 1.51045, 1.71511, 1.7...","[[1.0, 0.143370955, -0.6601173127, -0.22212161...","[-0.2912918773, -0.2912918773, -0.2912918773, ...","[2.0288821321, 2.0288821321, 2.0288821321, 2.0..."
Cr_pv6W_sv2.D0_19-A3B.FM,-42.039279,-42.05443,"[-5.3205290305, -5.3211668379, -5.3205290069, ...","[[0.0, 1.55611, -0.46190499999999995, 4.3839, ...","[[0.1014238266, 0.2121465775, 0.0408827474, 0....","[[0.0, -0.296833, -0.469329, -0.400833, -0.563...","[[0.0, 1.24744, 1.08305, 1.15153, 1.18244, 1.2...","[[1.0, 0.2025627613, -0.1508505882, -0.0780889...","[-0.2816017388, -0.2816017668, -0.2816209469, ...","[1.3882425276, 1.3882425434, 1.3883516161, 1.3..."
Cr_pv6W_sv2.D0_19-A3B.NM,-42.039279,-42.05443,"[-5.3205290305, -5.3211668379, -5.3205290069, ...","[[0.0, 1.55611, -0.46190499999999995, 4.3839, ...","[[0.1014238266, 0.2121465775, 0.0408827474, 0....","[[0.0, -0.296833, -0.469329, -0.400833, -0.563...","[[0.0, 1.24744, 1.08305, 1.15153, 1.18244, 1.2...","[[1.0, 0.2025627613, -0.1508505882, -0.0780889...","[-0.2816017388, -0.2816017668, -0.2816209469, ...","[1.3882425276, 1.3882425434, 1.3883516161, 1.3..."
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM,-143.858275,-177.797933,"[-5.6783573351, -5.6783573351, -5.6783573351, ...","[[0.0, 1.6417299999999997, -0.514678, 4.64595,...","[[0.0511669029, 0.1742224999, 0.0090822449, 0....","[[0.0, -0.313498, -0.0932309, -0.316523, -0.13...","[[0.0, 1.2813, 1.04399, 1.22413, 1.20185, 1.29...","[[1.0, 0.10219008189999998, -0.3019827453, -0....","[-0.158261488, -0.158261488, -0.158261488, -0....","[1.5465220577, 1.5465220577, 1.5465220577, 1.5..."
...,...,...,...,...,...,...,...,...,...,...
Cr_pv10W_sv3.mu-BAAAB.FM,-73.831298,-74.435034,"[-6.9191485421, -6.919148542, -6.9191513819, -...","[[0.0, 2.32545, -0.791208, 9.27675, -7.1620900...","[[0.0938956088, 0.1856862941, 0.0340534405, 0....","[[0.0, -0.340239, -0.261418, -0.680929, -0.326...","[[0.0, 1.52494, 1.24419, 1.6427599999999998, 1...","[[1.0, 0.1875274718, -0.2562981024, -0.1024407...","[-0.3404644258, -0.1911202335, -0.1911202335, ...","[1.8129944001, 1.7889585488, 1.7889585488, 1.7..."
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM,-156.777732,-172.917606,"[-5.0627343795, -5.0627343795, -5.0627343795, ...","[[0.0, 1.34753, -0.454488, 3.32921, -2.3634, 1...","[[0.0464940682, 0.1540991271, 0.0040858193, 0....","[[0.0, -0.337275, -0.124542, -0.254523, -0.055...","[[0.0, 1.16083, 1.00465, 1.17859, 1.15633, 1.2...","[[1.0, 0.0928575381, -0.3821768843, -0.1522285...","[-0.1384632371, -0.1384632371, -0.1384632371, ...","[1.4890419619, 1.4890419619, 1.4890419619, 1.4..."
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM,-156.777732,-172.917606,"[-5.0627343795, -5.0627343795, -5.0627343795, ...","[[0.0, 1.34753, -0.454488, 3.32921, -2.3634, 1...","[[0.0464940682, 0.1540991271, 0.0040858193, 0....","[[0.0, -0.337275, -0.124542, -0.254523, -0.055...","[[0.0, 1.16083, 1.00465, 1.17859, 1.15633, 1.2...","[[1.0, 0.0928575381, -0.3821768843, -0.1522285...","[-0.1384632371, -0.1384632371, -0.1384632371, ...","[1.4890419619, 1.4890419619, 1.4890419619, 1.4..."
Co_pv13W_sv16.chi-ABAB.NM,-127.090687,-186.802107,"[-5.1432538134, -5.1432538134, -5.1432538134, ...","[[0.0, 1.39375, -0.697376, 4.37561, -4.33507, ...","[[0.0845189587, 0.1662151375, 0.0140483303, 0....","[[0.0, -0.500358, -0.0628219, -0.437898, -0.25...","[[0.0, 1.18057, 1.22284, 1.25595, 1.24353, 1.1...","[[1.0, 0.16880051, -0.3338930785, -0.224126800...","[-0.2501789759, -0.220093001, -0.220093001, -0...","[1.4800169087, 1.5044601715, 1.5044601715, 1.5..."
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM,-143.858275,-177.797933,"[-5.6783573351, -5.6783573351, -5.6783573351, ...","[[0.0, 1.6417299999999997, -0.514678, 4.64595,...","[[0.0511669029, 0.1742224999, 0.0090822449, 0....","[[0.0, -0.313498, -0.0932309, -0.316523, -0.13...","[[0.0, 1.2813, 1.04399, 1.22413, 1.20185, 1.29...","[[1.0, 0.10219008189999998, -0.3019827453, -0....","[-0.158261488, -0.158261488, -0.158261488, -0....","[1.5465220577, 1.5465220577, 1.5465220577, 1.5..."

In [11]:
matrix_columns = BopFeatures.columns.drop(['U_bind','U_bond_atom', 'U_bond_atom_list'])

In [ ]:
matrix_columns

Index(['moments', 'normed_moments', 'an', 'bn', 'sigma', 'Ainf', 'Binf'], dtype='object')

In [15]:
MS = {}
for index, compound in BopFeatures['moments'].iteritems():
    m = np.array(compound)
    natoms, nm = m.shape
    MS[index] = {f'm{this}' :  m[:,this] for this in range(nm)}

In [17]:
MS = pd.DataFrame.from_dict(MS, orient='index')

In [18]:
MS

,m0,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,m15
Co_pv6W_sv6.C14-BBA.FM,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1.30409, 1.30409, 1.30409, 1.30409, 2.91668, ...","[-0.634205, -0.634205, -0.634205, -0.634205, -...","[4.08953, 4.08953, 4.08953, 4.08953, 14.5578, ...","[-4.29737, -4.29737, -4.29737, -4.29737, -12.0...","[19.0282, 19.0282, 19.0282, 19.0282, 94.3376, ...","[-29.648900000000005, -29.648900000000005, -29...","[115.535, 115.535, 115.535, 115.535, 751.386, ...","[-231.802, -231.802, -231.802, -231.802, -1498...","[858.923, 858.923, 858.923, 858.923, 7095.24, ...","[-2066.6, -2066.6, -2066.6, -2066.6, -18099.2,...","[7516.65, 7516.65, 7516.65, 7516.65, 76568.6, ...","[-20705.3, -20705.3, -20705.3, -20705.3, -2288...","[75043.3, 75043.3, 75043.3, 75043.3, 911609.0,...","[-228370.0, -228370.0, -228370.0, -228370.0, -...","[830861.0, 830861.0, 830861.0, 830861.0, 11633..."
Co_pv6W_sv6.C14-BBA.NM,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1.30409, 1.30409, 1.30409, 1.30409, 2.91668, ...","[-0.634205, -0.634205, -0.634205, -0.634205, -...","[4.08953, 4.08953, 4.08953, 4.08953, 14.5578, ...","[-4.29737, -4.29737, -4.29737, -4.29737, -12.0...","[19.0282, 19.0282, 19.0282, 19.0282, 94.3376, ...","[-29.648900000000005, -29.648900000000005, -29...","[115.535, 115.535, 115.535, 115.535, 751.386, ...","[-231.802, -231.802, -231.802, -231.802, -1498...","[858.923, 858.923, 858.923, 858.923, 7095.24, ...","[-2066.6, -2066.6, -2066.6, -2066.6, -18099.2,...","[7516.65, 7516.65, 7516.65, 7516.65, 76568.6, ...","[-20705.3, -20705.3, -20705.3, -20705.3, -2288...","[75043.3, 75043.3, 75043.3, 75043.3, 911609.0,...","[-228370.0, -228370.0, -228370.0, -228370.0, -...","[830861.0, 830861.0, 830861.0, 830861.0, 11633..."
Cr_pv6W_sv2.D0_19-A3B.FM,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]","[1.55611, 1.55611, 1.55636, 1.55611, 1.55636, ...","[-0.46190499999999995, -0.46190499999999995, -...","[4.3839, 4.3839, 4.38482, 4.3839, 4.38482, 4.3...","[-3.4185500000000006, -3.4185500000000006, -3....","[16.0556, 16.0556, 16.0593, 16.0556, 16.0593, ...","[-20.7775, -20.7775, -20.7816, -20.7775, -20.7...","[70.4179, 70.4179, 70.4334, 70.4179, 70.4334, ...","[-122.247, -122.247, -122.27000000000001, -122...","[353.515, 353.515, 353.586, 353.515, 353.586, ...","[-729.767, -729.767, -729.89, -729.767, -729.8...","[1964.3399999999997, 1964.3399999999997, 1964....","[-4492.52, -4492.52, -4493.18, -4492.52, -4493...","[11774.8, 11774.8, 11776.5, 11774.8, 11776.5, ...","[-28638.5, -28638.5, -28642.0, -28638.5, -2864...","[74709.1, 74709.1, 74718.0, 74709.1, 74718.0, ..."
Cr_pv6W_sv2.D0_19-A3B.NM,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]","[1.55611, 1.55611, 1.55636, 1.55611, 1.55636, ...","[-0.46190499999999995, -0.46190499999999995, -...","[4.3839, 4.3839, 4.38482, 4.3839, 4.38482, 4.3...","[-3.4185500000000006, -3.4185500000000006, -3....","[16.0556, 16.0556, 16.0593, 16.0556, 16.0593, ...","[-20.7775, -20.7775, -20.7816, -20.7775, -20.7...","[70.4179, 70.4179, 70.4334, 70.4179, 70.4334, ...","[-122.247, -122.247, -122.27000000000001, -122...","[353.515, 353.515, 353.586, 353.515, 353.586, ...","[-729.767, -729.767, -729.89, -729.767, -729.8...","[1964.3399999999997, 1964.3399999999997, 1964....","[-4492.52, -4492.52, -4493.18, -4492.52, -4493...","[11774.8, 11774.8, 11776.5, 11774.8, 11776.5, ...","[-28638.5, -28638.5, -28642.0, -28638.5, -2864...","[74709.1, 74709.1, 74718.0, 74709.1, 74718.0, ..."
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1.6417299999999997, 1.6417299999999997, 1.641...","[-0.514678, -0.514678, -0.514678, -0.514678, -...","[4.64595, 4.64595, 4.64595, 4.64595, 4.64595, ...","[-3.02923, -3.02923, -3.02923, -3.02923, -3.02...","[16.3899, 16.3899, 16.3899, 16.3899, 16.3899, ...","[-16.0806, -16.0806, -16.0806, -16.0806, -16.0...","[66.5632, 66.5632, 66.5632, 66.5632, 66.5632, ...","[-85.3979, -85.3979, -85.3979, -85.3979, -85.3...","[299.831, 299.831, 299.831, 299.831, 299.831, ...","[-463.3450000000001, -463.3450000000001, -463....","[1464.19, 1464.19, 1464.19, 1464.19, 1464.19, ...","[-2584.97, -2584.97, -2584.97, -2584.97, -2584...","[7637.729999999999, 7637.729999999999, 7637.72...","[-14875.1, -14875.1, -14875.1, -14875.1, -1487...","[42162.7, 42162.7, 42162.7, 42162.7, 42162.7, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cr_pv10W_sv3.mu-BAAAB.FM,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[2.32545, 2.44747, 2.44747, 2.44747, 2.44747, ...","[-0.791208, -0.791261, -0.791261, -0.791262, -...","[9.27675, 10.2647, 10.2647, 10.2647, 10.2647, ...","[-7.162090000000001, -6.923019999999999, -6.92...","[48.651, 55.892399999999995, 55.89239999999999...","[-63.19690000000001, -58.1865, -58.1865, -58.1...","[315.388, 365.616, 365.616, 365.617, 365.616, ...","[-583.135, -522.322, -522.322, -522.322, -522....","[2412.57, 2749.73, 2749.73, 2749.73, 2749.73, ...","[-5617.25, -4998.23, -4998.23, -4998.23, -4998...","[20860.5, 23041.0, 23041.0, 23041.0, 23041.0, ...","[-56123.3, -50169.1, -50169.1, -50169.1, -5016...","[196733.0, 209781.0, 209781.0, 209781.0, 20978...","[-578225.0, -521162.0, -521162.0, -521163.0, -...","[1970590.0, 2033730.0, 2033730.0, 2033730.0, 2..."
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1.34753, 1.34753, 1.34753, 1.34753, 1.56491, ...","[-0.454488, -0.454488, -0.454488, -0.454488, -...","[3.32921, 3.32921, 3.32921, 3.32921, 4.22135, ...","[-2.3634, -2.3634, -2.3634, -2.3634, -2.68722,...","[10.611, 10.611, 10.611, 10.611, 14.1952, 14.1...","[-11.1659, -11.1659, -11.1659, -11.1659, -13.5...","[39.594, 39.594, 39.594, 39.594, 54.9525, 54.9...","[-53.031600000000005, -53.031600000000005, -53...","[164.539, 164.539, 164.539, 164.539, 235.949, ...","[-257.548, -257.548, -257.548, -257.548, -355....","[738.16, 738.16, 738.16, 738.16, 1098.31, 1098...","[-1281.35, -1281.35, -1281.35, -1281.35, -1893...","[3503.2300000000005, 3503.2300000000005, 3503....","[-6524.74, -6524.74, -6524.74, -6524.74, -1038...","[17362.6, 17362.6, 17362.6, 17362.6, 28736.6, ..."
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1.34753, 1.34753, 1.34753, 1.34753, 1.56491, ...","[-0.454488, -0.454488, -0.454488, -0.454488, -...","[3.32921, 3.32921, 3.32921, 3.32921, 4.22135, ...","[-2.3634, -2.3634, -2.3634, -2.3634, -2.68722,...","[10.611, 10.611, 10.611, 10.611, 14.1952, 14.1...","[-11.1659, -11.1659, -11.1659, -11.1659, -13.5...","[39.594, 39.594, 39.594, 39.594, 54.9525, 54.9...","[-53.031600000000005, -53.031600000000005, -53...","[164.539, 164.539, 164.539, 164.539, 235.949, ...","[-257.548, -257.548, -257.548, -257.548, -355....","[738.16, 738.16, 738.16, 738.16, 1098.31, 1098...","[-1281.35, -1281.35, -1281.35, -1281.35, -1893...","[3503.2300000000005, 3503.2300000000005, 3503....","[-6524.74, -6524.74, -6524.74, -6524.74, -1038...","[17362.6, 17362.6, 17362.6, 17362.6, 28736.6, ..."
Co_pv13W_sv16.chi-ABAB.NM,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1.39375, 1.584, 1.584, 1.584, 1.584, 2.0259, ...","[-0.697376, -0.697257, -0.697257, -0.697257, -...","[4.37561, 5.24538, 5.24538, 5.24538, 5.24538, ...","[-4.33507, -4.67131, -4.67131, -4.67131, -4.67...","[18.1718, 22.9519, 22.9519, 22.9519, 22.9519, ...","[-25.53, -29.6504, -29.6504, -29.6504, -29.650...","[88.0747, 117.149, 117.149, 117.149, 117.149, ...","[-153.449, -192.147, -192.147, -192.147, -192....","[471.713, 661.331, 661.331, 661.331, 661.331, ...","[-944.543, -1274.89, -1274.89, -1274.89, -1274...","[2707.62, 4011.9199999999996, 4011.91999999999...","[-5939.67, -8639.64, -8639.64, -8639.64, -8639...","[16339.6, 25682.8, 25682.8, 25682.8, 25682.8, ...","[-38080.6, -59687.5, -59687.5, -59687.5, -5968...","[102378.0, 171347.0, 171347.0, 171347.0, 17134..."
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1.6417299999999997, 1.6417299999999997, 1.641...","[-0.514678, -0.514678, -0.514678, -0.514678, -...","[4.64595, 4.64595, 4.64595, 4.64595, 4.64595, ...","[-3.02923, -3.02923, -3.02923, -3.02923, -3.02...","[16.3899, 16.3899, 16.3899, 16.3899, 16.3899, ...","[-16.0806, -16.0806, -16.0806, -16.0806, -16.0...","[66.5632, 66.5632, 66.5632, 66.5632, 66.5632, ...","[-85.3979, -85.3979, -85.3979, -85.3979, -85.3...","[299.831, 299.831, 299.831, 299.831, 299.831, ...","[-463.3450000000001, -463.3450000000001, -463....","[1464.19, 1464.19, 1464.19, 1464.19, 1464.19, ...","[-2584.97, -2584.97, -2584.97, -2584.97, -2584...","[7637.729999999999, 7637.729999999999, 7637.72...","[-14875.1, -14875.1, -14875.1, -14875.1, -1487...","[42162.7, 42162.7, 42162.7, 42162.7, 42162.7, ..."

In [19]:
MSAveraged = gf.cnaverage_dataframe(MS, MS.columns, PyscalFeatures.pyscal_cn,)

cnaverage m0

  0%|          | 0/1681 [00:00<?, ?it/s]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

# Compositional Features