# Prepare the features

- BOP features arrangement and averagings
- Library Features arrangement ad averaging
- Matminer features cleanup (decide min, max or avg)
- clear feature list from correlations
- outlier detection based on features
- Feature Distribution plots

 - input : features dataframes from prev steps
 - output: clean features dataframes into picles

In [10]:
import pandas as pd
import numpy as np

In [19]:
Compositional = pd.read_pickle('Cr-Co-W/matminer_composition_features.pkl')

In [20]:
Atomic = pd.read_pickle('Cr-Co-W/matminer_atomic_features.pkl')

In [5]:
BOP = pd.read_pickle('Cr-Co-W/Descriptors/CrCoW_initial_canonical_table_WUBIND_16.pkl')

In [12]:
M0 = np.array(BOP['normed_moments'][0])

In [13]:
m1 = M0[:,0]

In [14]:
m1

array([0.0717863 , 0.0717863 , 0.0717863 , 0.0717863 , 0.08862682,
       0.08862682, 0.06890775, 0.06890775, 0.06890773, 0.06890775,
       0.06890775, 0.06890773])

In [15]:
NEWBOP = {BOP.index[0]: {'m1': m1}}

In [16]:
NEWBOP

{'Co_pv6W_sv6.C14-BBA.FM': {'m1': array([0.0717863 , 0.0717863 , 0.0717863 , 0.0717863 , 0.08862682,
         0.08862682, 0.06890775, 0.06890775, 0.06890773, 0.06890775,
         0.06890775, 0.06890773])}}

In [18]:
Compositional

,HOMO_energy,LUMO_energy,band center,,B,E0,V,deltak,encut,fit,...,W_sv,Mag,EF,composition,0-norm,2-norm,3-norm,5-norm,7-norm,10-norm
index,,,,,,,,,,,,,,,,,,,,,
Co_pv6W_sv6.C14-BBA.FM,-0.220603,-0.220603,-2.311715,bulk C14-BBA.FM,293.907391 GPa,-10.000427,13.175678 A,0.020,400,murnaghan volume_relaxed,...,0.500000,2,-0.038167,"(Co, W)",2,0.913625,0.909394,0.909093,0.909091,0.909091
Co_pv6W_sv6.C14-BBA.NM,-0.220603,-0.220603,-2.311715,bulk C14-BBA,293.949578 GPa,-10.000427,13.175679 A,0.020,400,murnaghan volume_relaxed,...,0.500000,0,-0.038167,"(Co, W)",2,0.913625,0.909394,0.909093,0.909091,0.909091
Cr_pv6W_sv2.D0_19-A3B.FM,-0.220603,-0.220603,-2.175953,bulk D0_19-A3B.FM,244.993002 GPa,-10.002413,13.098145 A,0.020,400,murnaghan volume_relaxed,...,0.250000,2,0.272512,"(Cr, W)",2,0.803101,0.776092,0.769604,0.769255,0.769231
Cr_pv6W_sv2.D0_19-A3B.NM,-0.220603,-0.220603,-2.175953,bulk D0_19-A3B,248.338396 GPa,-10.002452,13.093819 A,0.020,400,murnaghan volume_relaxed,...,0.250000,0,0.272473,"(Cr, W)",2,0.803101,0.776092,0.769604,0.769255,0.769231
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM,-0.150445,-0.150445,-1.897795,bulk sigma-CBAAC.FM,243.415325 GPa,-10.003732,13.525828 A,0.020,400,murnaghan volume_relaxed,...,0.333333,2,0.247342,"(Cr, Co, W)",3,0.642910,0.576008,0.543235,0.536132,0.533816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM,-0.118123,-0.118123,-1.838481,bulk sigma-BAACA.FM,251.093896 GPa,-9.988760,13.189987 A,0.020,400,murnaghan volume_relaxed,...,0.266667,2,0.184951,"(Cr, Co, W)",3,0.721110,0.680809,0.668028,0.666823,0.666674
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM,-0.118123,-0.118123,-1.838481,bulk sigma-BAACA,251.071094 GPa,-9.988760,13.189913 A,0.020,400,murnaghan volume_relaxed,...,0.266667,0,0.184951,"(Cr, Co, W)",3,0.721110,0.680809,0.668028,0.666823,0.666674
Co_pv13W_sv16.chi-ABAB.NM,-0.220603,-0.220603,-2.320017,bulk chi-ABAB,263.749012 GPa,-9.988843,14.051746 A,0.020,400,murnaghan volume_relaxed,...,0.551724,0,0.282865,"(Co, W)",2,0.927903,0.925021,0.924856,0.924855,0.924855
Co_pv13W_sv16.chi-ABAB.FM,-0.220603,-0.220603,-2.320017,bulk chi-ABAB.FM,426.930807 GPa,-9.993120,14.075905 A,0.020,400,murnaghan volume_relaxed,...,0.551724,2,0.278588,"(Co, W)",2,0.927903,0.925021,0.924856,0.924855,0.924855
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM,-0.150445,-0.150445,-1.897795,bulk sigma-CBAAC,237.775710 GPa,-9.997783,13.488365 A,0.020,400,murnaghan volume_relaxed,...,0.333333,0,0.253291,"(Cr, Co, W)",3,0.642910,0.576008,0.543235,0.536132,0.533816

In [21]:
Atomic

,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,MagpieData maximum MendeleevNumber,MagpieData range MendeleevNumber,MagpieData mean MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
Co_pv6W_sv6.C14-BBA.FM,27.0,74.0,47.0,69.727273,7.768595,74.0,51.0,58.0,7.0,51.636364,...,1.548471,0.140770,0.255946,0.0,194.0,229.0,35.0,225.818182,5.785124,229.0
Co_pv6W_sv6.C14-BBA.NM,27.0,74.0,47.0,69.727273,7.768595,74.0,51.0,58.0,7.0,51.636364,...,1.548471,0.140770,0.255946,0.0,194.0,229.0,35.0,225.818182,5.785124,229.0
Cr_pv6W_sv2.D0_19-A3B.FM,24.0,74.0,50.0,62.461538,17.751479,74.0,49.0,51.0,2.0,50.538462,...,0.000000,0.000000,0.000000,0.0,229.0,229.0,0.0,229.000000,0.000000,229.0
Cr_pv6W_sv2.D0_19-A3B.NM,24.0,74.0,50.0,62.461538,17.751479,74.0,49.0,51.0,2.0,50.538462,...,0.000000,0.000000,0.000000,0.0,229.0,229.0,0.0,229.000000,0.000000,229.0
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM,24.0,74.0,50.0,41.066667,21.955556,24.0,49.0,58.0,9.0,50.866667,...,1.548471,0.206463,0.357869,0.0,194.0,229.0,35.0,224.333333,8.088889,229.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cr_pv10W_sv3.mu-BAAAB.FM,24.0,74.0,50.0,61.500000,18.750000,74.0,49.0,51.0,2.0,50.500000,...,0.000000,0.000000,0.000000,0.0,229.0,229.0,0.0,229.000000,0.000000,229.0
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM,24.0,74.0,50.0,37.533333,19.448889,24.0,49.0,58.0,9.0,50.133333,...,1.548471,0.103231,0.192699,0.0,194.0,229.0,35.0,226.666667,4.355556,229.0
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM,24.0,74.0,50.0,37.533333,19.448889,24.0,49.0,58.0,9.0,50.133333,...,1.548471,0.103231,0.192699,0.0,194.0,229.0,35.0,226.666667,4.355556,229.0
Co_pv13W_sv16.chi-ABAB.NM,27.0,74.0,47.0,70.468208,6.532794,74.0,51.0,58.0,7.0,51.526012,...,1.548471,0.116359,0.215231,0.0,194.0,229.0,35.0,226.369942,4.864847,229.0
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM,24.0,74.0,50.0,41.066667,21.955556,24.0,49.0,58.0,9.0,50.866667,...,1.548471,0.206463,0.357869,0.0,194.0,229.0,35.0,224.333333,8.088889,229.0

In [26]:
Atomic.columns.str.contains('mean')

array([False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False])

In [ ]:
from seaborn