In [1]:
import pickle
import pandas
import os
from Tools.DatasetTools.DatasetOperator import Dataset, DatasetTester

In [2]:
target_case = 'EF_nmhcp'

In [3]:
ModelName = 'Kernel Ridge'

In [4]:
import logging
Logger = logging.getLogger()
Logger.setLevel(logging.INFO)
logging.basicConfig(format='%(message)s')

In [5]:
namefile = ModelName.replace(' ', '')
suffix = f"no_hcp_bcc_fcc_{namefile}" #'CV_restart_folds_inloop''CV_restart_folds_inloop

In [6]:
dataset = 'Fe-Mo'

In [7]:
DS = Dataset('Fe-Mo', target_name=target_case, remove_phases_query='Phase != "bcc" and Phase != "fcc" and Phase !="hcp"')

In [8]:
feature_concat_resul_loc = os.path.join(dataset, 'results', f'concatenation_results_{target_case}_{suffix}.pkl')  
if os.path.exists(feature_concat_resul_loc):
    with open(feature_concat_resul_loc, 'rb') as pkl:
        savedFCresults = pickle.load(pkl)
else:
    savedFCresults = {}

In [9]:
savedFCresults[(ModelName, 'atomic no CNAV')]

[                                     train1     test1  \
 MagpieData mean GSmagmom           0.144313  0.146840
 Structure                          0.127471  0.138823
 MagpieData maximum Row             0.125671  0.142002
 MagpieData minimum AtomicWeight    0.123107  0.141536
 MagpieData mode NsValence          0.115461  0.139977
 MagpieData avg_dev Number          0.105383  0.141100
 Mag                                0.097627  0.146766
 MagpieData mode Electronegativity  0.093689  0.148566

                                                                               params  \
 MagpieData mean GSmagmom           {'regressor__alpha': 1.0, 'regressor__coef0': ...
 Structure                          {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData maximum Row             {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData minimum AtomicWeight    {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode NsValence          {'regressor__alpha': 0.1, 'regressor__coef0': ...
 MagpieData avg_dev Number          {'regressor__alpha': 0.1, 'regressor__coef0': ...
 Mag                                {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode Electronegativity  {'regressor__alpha': 1.0, 'regressor__coef0': ...

                                        test     train
 MagpieData mean GSmagmom           0.145459  0.144785
 Structure                          0.132305  0.129509
 MagpieData maximum Row             0.134831  0.131056
 MagpieData minimum AtomicWeight    0.138943  0.130695
 MagpieData mode NsValence          0.141031  0.123262
 MagpieData avg_dev Number          0.146646  0.121339
 Mag                                0.147410  0.138883
 MagpieData mode Electronegativity  0.150883  0.138520  ,
                                       train1     test1  \
 MagpieData mean AtomicWeight        0.144164  0.146517
 Structure                           0.127462  0.137319
 MagpieData maximum MendeleevNumber  0.125857  0.137208
 Mag                                 0.120392  0.146468
 MagpieData minimum Column           0.119115  0.146230
 MagpieData avg_dev Column           0.108881  0.147434
 MagpieData mode Column              0.098905  0.150461
 MagpieData mode Electronegativity   0.094747  0.150931

                                                                                params  \
 MagpieData mean AtomicWeight        {'regressor__alpha': 1.0, 'regressor__coef0': ...
 Structure                           {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData maximum MendeleevNumber  {'regressor__alpha': 1.0, 'regressor__coef0': ...
 Mag                                 {'regressor__alpha': 0.01, 'regressor__coef0':...
 MagpieData minimum Column           {'regressor__alpha': 0.01, 'regressor__coef0':...
 MagpieData avg_dev Column           {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode Column              {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode Electronegativity   {'regressor__alpha': 1.0, 'regressor__coef0': ...

                                         test     train
 MagpieData mean AtomicWeight        0.145607  0.144793
 Structure                           0.131878  0.129347
 MagpieData maximum MendeleevNumber  0.133124  0.129145
 Mag                                 0.130441  0.128022
 MagpieData minimum Column           0.133176  0.127318
 MagpieData avg_dev Column           0.146613  0.139046
 MagpieData mode Column              0.147410  0.138883
 MagpieData mode Electronegativity   0.150883  0.138520  ,
                                      train1     test1  \
 MagpieData mean AtomicWeight       0.144062  0.147102
 Structure                          0.127011  0.141225
 MagpieData maximum CovalentRadius  0.125590  0.142668
 MagpieData minimum GSvolume_pa     0.123275  0.140998
 MagpieData mode CovalentRadius     0.110655  0.138573
 MagpieData mode NValence           0.111185  0.138724
 Mag                                0.102744  0.151324
 MagpieData avg_dev NsValence       0.093644  0.150798
 random                             0.051729  0.153805

                                                                               params  \
 MagpieData mean AtomicWeight       {'regressor__alpha': 1.0, 'regressor__coef0': ...
 Structure                          {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData maximum CovalentRadius  {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData minimum GSvolume_pa     {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode CovalentRadius     {'regressor__alpha': 0.01, 'regressor__coef0':...
 MagpieData mode NValence           {'regressor__alpha': 0.01, 'regressor__coef0':...
 Mag                                {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData avg_dev NsValence       {'regressor__alpha': 1.0, 'regressor__coef0': ...
 random                             {'regressor__alpha': 1.0, 'regressor__coef0': ...

                                        test     train
 MagpieData mean AtomicWeight       0.145607  0.144793
 Structure                          0.132305  0.129509
 MagpieData maximum CovalentRadius  0.132357  0.130340
 MagpieData minimum GSvolume_pa     0.136244  0.129829
 MagpieData mode CovalentRadius     0.143396  0.114928
 MagpieData mode NValence           0.143579  0.115192
 Mag                                0.151147  0.139858
 MagpieData avg_dev NsValence       0.150883  0.138520
 random                             0.150743  0.135840  ,
                                       train1     test1  \
 MagpieData mean AtomicWeight        0.143984  0.146792
 Structure                           0.127421  0.140721
 MagpieData minimum NsUnfilled       0.125673  0.140507
 MagpieData minimum GSmagmom         0.123526  0.142984
 MagpieData mode Column              0.115082  0.145116
 MagpieData mode Number              0.111010  0.144602
 Mag                                 0.102455  0.152268
 random                              0.071777  0.152920
 MagpieData avg_dev MendeleevNumber  0.058645  0.152145

                                                                                params  \
 MagpieData mean AtomicWeight        {'regressor__alpha': 1.0, 'regressor__coef0': ...
 Structure                           {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData minimum NsUnfilled       {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData minimum GSmagmom         {'regressor__alpha': 0.1, 'regressor__coef0': ...
 MagpieData mode Column              {'regressor__alpha': 0.01, 'regressor__coef0':...
 MagpieData mode Number              {'regressor__alpha': 0.01, 'regressor__coef0':...
 Mag                                 {'regressor__alpha': 1.0, 'regressor__coef0': ...
 random                              {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData avg_dev MendeleevNumber  {'regressor__alpha': 1.0, 'regressor__coef0': ...

                                         test     train
 MagpieData mean AtomicWeight        0.145607  0.144793
 Structure                           0.131740  0.129343
 MagpieData minimum NsUnfilled       0.133706  0.129258
 MagpieData minimum GSmagmom         0.139882  0.131295
 MagpieData mode Column              0.143293  0.118229
 MagpieData mode Number              0.143579  0.115192
 Mag                                 0.151147  0.139858
 random                              0.148012  0.137246
 MagpieData avg_dev MendeleevNumber  0.148610  0.135971  ,
                                    train1     test1  \
 MagpieData mean AtomicWeight     0.144304  0.146226
 Structure                        0.127044  0.140921
 MagpieData maximum AtomicWeight  0.125496  0.142162
 MagpieData minimum MeltingT      0.123009  0.142361
 MagpieData mode AtomicWeight     0.111323  0.139729
 MagpieData mode NValence         0.111514  0.142534
 Mag                              0.103112  0.153339
 random                           0.072739  0.151420
 MagpieData avg_dev AtomicWeight  0.059034  0.150285

                                                                             params  \
 MagpieData mean AtomicWeight     {'regressor__alpha': 1.0, 'regressor__coef0': ...
 Structure                        {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData maximum AtomicWeight  {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData minimum MeltingT      {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode AtomicWeight     {'regressor__alpha': 0.1, 'regressor__coef0': ...
 MagpieData mode NValence         {'regressor__alpha': 0.01, 'regressor__coef0':...
 Mag                              {'regressor__alpha': 1.0, 'regressor__coef0': ...
 random                           {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData avg_dev AtomicWeight  {'regressor__alpha': 1.0, 'regressor__coef0': ...

                                      test     train
 MagpieData mean AtomicWeight     0.145607  0.144793
 Structure                        0.132305  0.129509
 MagpieData maximum AtomicWeight  0.134831  0.131056
 MagpieData minimum MeltingT      0.138943  0.130695
 MagpieData mode AtomicWeight     0.145093  0.120638
 MagpieData mode NValence         0.143579  0.115192
 Mag                              0.151147  0.139858
 random                           0.148012  0.137246
 MagpieData avg_dev AtomicWeight  0.148610  0.135971  ,
                                      train1     test1  \
 MagpieData mean AtomicWeight       0.144258  0.146649
 random                             0.139228  0.148757
 MagpieData avg_dev NsUnfilled      0.133176  0.146080
 Mag                                0.116196  0.146551
 MagpieData minimum CovalentRadius  0.113999  0.147619
 MagpieData mode MendeleevNumber    0.098462  0.149023
 MagpieData maximum AtomicWeight    0.099050  0.148420
 MagpieData mode AtomicWeight       0.096120  0.150071
 Structure                          0.060682  0.150154

                                                                               params  \
 MagpieData mean AtomicWeight       {'regressor__alpha': 1.0, 'regressor__coef0': ...
 random                             {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData avg_dev NsUnfilled      {'regressor__alpha': 1.0, 'regressor__coef0': ...
 Mag                                {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData minimum CovalentRadius  {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode MendeleevNumber    {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData maximum AtomicWeight    {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode AtomicWeight       {'regressor__alpha': 1.0, 'regressor__coef0': ...
 Structure                          {'regressor__alpha': 1.0, 'regressor__coef0': ...

                                        test     train
 MagpieData mean AtomicWeight       0.145607  0.144793
 random                             0.143607  0.143111
 MagpieData avg_dev NsUnfilled      0.144718  0.141970
 Mag                                0.141881  0.140630
 MagpieData minimum CovalentRadius  0.140118  0.140075
 MagpieData mode MendeleevNumber    0.141415  0.132996
 MagpieData maximum AtomicWeight    0.138734  0.133105
 MagpieData mode AtomicWeight       0.140194  0.138971
 Structure                          0.148610  0.135971  ,
                                       train1     test1  \
 MagpieData mean NsUnfilled          0.144217  0.146425
 MagpieData minimum MeltingT         0.143732  0.146063
 Structure                           0.124809  0.142117
 MagpieData maximum NsUnfilled       0.122706  0.144740
 Mag                                 0.118271  0.148930
 MagpieData avg_dev MendeleevNumber  0.107982  0.147474
 MagpieData mode GSmagmom            0.098293  0.148624
 random                              0.063538  0.149560
 MagpieData mode Electronegativity   0.060294  0.150411

                                                                                params  \
 MagpieData mean NsUnfilled          {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData minimum MeltingT         {'regressor__alpha': 1.0, 'regressor__coef0': ...
 Structure                           {'regressor__alpha': 0.1, 'regressor__coef0': ...
 MagpieData maximum NsUnfilled       {'regressor__alpha': 0.1, 'regressor__coef0': ...
 Mag                                 {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData avg_dev MendeleevNumber  {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode GSmagmom            {'regressor__alpha': 1.0, 'regressor__coef0': ...
 random                              {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode Electronegativity   {'regressor__alpha': 1.0, 'regressor__coef0': ...

                                         test     train
 MagpieData mean NsUnfilled          0.145607  0.144793
 MagpieData minimum MeltingT         0.146393  0.144311
 Structure                           0.136255  0.131375
 MagpieData maximum NsUnfilled       0.140101  0.131409
 Mag                                 0.147508  0.142354
 MagpieData avg_dev MendeleevNumber  0.146613  0.139046
 MagpieData mode GSmagmom            0.147199  0.138821
 random                              0.147729  0.138128
 MagpieData mode Electronegativity   0.151218  0.137683  ,
                                       train1     test1  \
 MagpieData mode GSmagmom            0.147916  0.149683
 random                              0.144196  0.151748
 MagpieData avg_dev Column           0.133362  0.150912
 Mag                                 0.121363  0.153840
 MagpieData maximum MendeleevNumber  0.119700  0.155970
 MagpieData maximum MeltingT         0.119745  0.153696
 MagpieData mean NdValence           0.104930  0.153693
 MagpieData mode Electronegativity   0.103823  0.155515
 Structure                           0.060217  0.158855

                                                                                params  \
 MagpieData mode GSmagmom            {'regressor__alpha': 1.0, 'regressor__coef0': ...
 random                              {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData avg_dev Column           {'regressor__alpha': 1.0, 'regressor__coef0': ...
 Mag                                 {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData maximum MendeleevNumber  {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData maximum MeltingT         {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mean NdValence           {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode Electronegativity   {'regressor__alpha': 1.0, 'regressor__coef0': ...
 Structure                           {'regressor__alpha': 1.0, 'regressor__coef0': ...

                                         test     train
 MagpieData mode GSmagmom            0.148273  0.148264
 random                              0.146678  0.146007
 MagpieData avg_dev Column           0.147191  0.141050
 Mag                                 0.142807  0.138756
 MagpieData maximum MendeleevNumber  0.143358  0.138321
 MagpieData maximum MeltingT         0.145765  0.141811
 MagpieData mean NdValence           0.144061  0.140917
 MagpieData mode Electronegativity   0.145927  0.140852
 Structure                           0.151218  0.137683  ,
                                         train1     test1  \
 MagpieData mean NsUnfilled            0.144384  0.146022
 Structure                             0.127123  0.141934
 MagpieData maximum GSmagmom           0.125375  0.140336
 Mag                                   0.118776  0.147215
 MagpieData avg_dev Column             0.105568  0.146838
 MagpieData maximum Electronegativity  0.107472  0.146404
 random                                0.079324  0.144105
 MagpieData mode Electronegativity     0.056734  0.143111
 MagpieData mode MendeleevNumber       0.056155  0.144717

                                                                                  params  \
 MagpieData mean NsUnfilled            {'regressor__alpha': 1.0, 'regressor__coef0': ...
 Structure                             {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData maximum GSmagmom           {'regressor__alpha': 1.0, 'regressor__coef0': ...
 Mag                                   {'regressor__alpha': 0.1, 'regressor__coef0': ...
 MagpieData avg_dev Column             {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData maximum Electronegativity  {'regressor__alpha': 1.0, 'regressor__coef0': ...
 random                                {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode Electronegativity     {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode MendeleevNumber       {'regressor__alpha': 1.0, 'regressor__coef0': ...

                                           test     train
 MagpieData mean NsUnfilled            0.145607  0.144793
 Structure                             0.132305  0.129509
 MagpieData maximum GSmagmom           0.133706  0.129258
 Mag                                   0.134732  0.129178
 MagpieData avg_dev Column             0.147394  0.139617
 MagpieData maximum Electronegativity  0.146613  0.139046
 random                                0.146621  0.135447
 MagpieData mode Electronegativity     0.151691  0.133679
 MagpieData mode MendeleevNumber       0.153797  0.132810  ,
                                    train1     test1  \
 MagpieData mean GSmagmom         0.144137  0.147940
 MagpieData minimum AtomicWeight  0.143750  0.147593
 Structure                        0.124927  0.144719
 MagpieData maximum MeltingT      0.123236  0.146463
 Mag                              0.117799  0.152320
 MagpieData avg_dev Row           0.108528  0.151154
 MagpieData mode GSmagmom         0.098604  0.151640
 MagpieData mode NUnfilled        0.094083  0.155406

                                                                             params  \
 MagpieData mean GSmagmom         {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData minimum AtomicWeight  {'regressor__alpha': 0.01, 'regressor__coef0':...
 Structure                        {'regressor__alpha': 0.01, 'regressor__coef0':...
 MagpieData maximum MeltingT      {'regressor__alpha': 0.01, 'regressor__coef0':...
 Mag                              {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData avg_dev Row           {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode GSmagmom         {'regressor__alpha': 1.0, 'regressor__coef0': ...
 MagpieData mode NUnfilled        {'regressor__alpha': 1.0, 'regressor__coef0': ...

                                      test     train
 MagpieData mean GSmagmom         0.145459  0.144785
 MagpieData minimum AtomicWeight  0.147183  0.144261
 Structure                        0.134221  0.131155
 MagpieData maximum MeltingT      0.137975  0.125466
 Mag                              0.147515  0.142368
 MagpieData avg_dev Row           0.146598  0.139062
 MagpieData mode GSmagmom         0.147410  0.138883
 MagpieData mode NUnfilled        0.150883  0.138520  ]

In [10]:
cleanfcresults = {}
for combi, fcresults in savedFCresults.items():
    ncurves = len(fcresults)
    if ModelName not in combi:
        Logger.info(f'{combi} is not {ModelName}')
        continue
    if ncurves < 1:
        Logger.info(f'{combi} has no curves')
        continue
    Logger.info(f'combi: {combi}, curves: {ncurves}')
    cleanfcresults[combi] = []
    for i, curve in enumerate(fcresults):
        if 'random' in curve.index:
            random_in = curve.index.get_loc('random')
        else:
            random_in = len(curve.index)
        cleancurve = curve.iloc[:,:random_in]
        nfeats = cleancurve.shape[0]
        if nfeats > 0:
            cleanfcresults[combi].append(curve)
#            Logger.info(f'curve {i}, nselected = {curve.shape}, random in: {random_in}, features clean: {nfeats}')

combi: ('Kernel Ridge', 'atomic'), curves: 3
combi: ('Kernel Ridge', 'dataset'), curves: 3
combi: ('Kernel Ridge', 'Canonical ACE'), curves: 12
combi: ('Kernel Ridge', 'Canonical BOP'), curves: 13
combi: ('Kernel Ridge', 'ACE no CNAV'), curves: 10
combi: ('Kernel Ridge', 'ACE'), curves: 12
combi: ('Kernel Ridge', '0.7dProjections 0.5OS BOP'), curves: 12
combi: ('Kernel Ridge', '0.7spProjections 0.5OS BOP'), curves: 13
combi: ('Kernel Ridge', 'atomic no CNAV'), curves: 10
combi: ('Kernel Ridge', 'dataset no CNAV'), curves: 10
combi: ('Kernel Ridge', '0.7dProjections 0.5OS BOP no CNAV'), curves: 10
combi: ('Kernel Ridge', '0.7spProjections 0.5OS BOP no CNAV'), curves: 10
combi: ('Kernel Ridge', 'SOAP_specific_small'), curves: 10
combi: ('Kernel Ridge', 'SOAP_specific_small no CNAV'), curves: 10
combi: ('Kernel Ridge', 'Canonical ACE no CNAV'), curves: 10
combi: ('Kernel Ridge', 'Canonical BOP no CNAV'), curves: 67
combi: ('Kernel Ridge', 'SOAP_canonicalW_small'), curves: 10
combi: ('Kernel Ridge', 'SOAP_canonicalW_small no CNAV'), curves: 10
combi: ('Kernel Ridge', '0.7dProjections 10scf 8.0jii BOP'), curves: 1
combi: ('Kernel Ridge', '0.7dProjections 10scf 8.0jii BOP no CNAV'), curves: 1
('Kernel Ridge', '0.7dProjections 100scf 8.0jii BOP') has no curves
('Kernel Ridge', '0.7dProjections 100scf 8.0jii BOP no CNAV') has no curves

test by learning

In [11]:
from Tools.DatasetTools.MLConveniences import filter_features
import joblib
dataset='Fe-Mo'

In [12]:
models = [ModelName]

In [13]:
modelnames=[model.replace(' ','') for model in models]

In [14]:
voting_regressor_files = {modelname: os.path.join(dataset, 'results', f'voting_regressor_{modelname}.pkl')
                         for modelname in modelnames}

In [15]:
voting_regressor_files

{'KernelRidge': 'Fe-Mo/results/voting_regressor_KernelRidge.pkl'}

In [16]:
optimal_regressors = {}
for model in modelnames:
    optimal_regressors.update(joblib.load(voting_regressor_files[model]))

In [17]:
redbold = "\x1b[31;1m"
reset = "\x1b[0m"

In [18]:
problematic_estimators = {}
for ( model, featurename ), votingregressor in optimal_regressors.items():
    estimators = votingregressor.estimators
    Logger.info(f'model:{model}, featurename: {featurename}, nestimators :{len(estimators)}' )
    X = DS.Features[featurename]
    problematic_estimators[(model, featurename)]=[]
    for iestimator, estimator in estimators:
        learning_curve = estimator.named_steps.feature_selection.kw_args['learning_curve']
        nfeatures = learning_curve.shape
        transformed_X =estimator.named_steps.feature_selection.transform(X)
        if transformed_X.shape[1] < 1:
            Logger.warning(f'{redbold}index{iestimator}, transformed curve length is ZERO (0){reset}')
            problematic_estimators[(model, featurename)].append(iestimator)
            continue
        Logger.info(f'index:{iestimator}, transformer curve length: {nfeatures}, nfeatures stranformed: {transformed_X.shape}')

model:Kernel Ridge, featurename: atomic, nestimators :3
index:0, transformer curve length: (8, 5), nfeatures stranformed: (262, 1)
index:1, transformer curve length: (8, 5), nfeatures stranformed: (262, 2)
index:2, transformer curve length: (8, 5), nfeatures stranformed: (262, 1)
model:Kernel Ridge, featurename: dataset, nestimators :3
index:0, transformer curve length: (21, 5), nfeatures stranformed: (262, 8)
index:1, transformer curve length: (8, 5), nfeatures stranformed: (262, 4)
index:2, transformer curve length: (17, 5), nfeatures stranformed: (262, 7)
model:Kernel Ridge, featurename: Canonical ACE, nestimators :12
index:0, transformer curve length: (202, 5), nfeatures stranformed: (262, 72)
index:1, transformer curve length: (199, 5), nfeatures stranformed: (262, 74)
index:2, transformer curve length: (132, 5), nfeatures stranformed: (262, 98)
index:3, transformer curve length: (95, 5), nfeatures stranformed: (262, 4)
index:4, transformer curve length: (143, 5), nfeatures stranformed: (262, 23)
index:5, transformer curve length: (198, 5), nfeatures stranformed: (262, 152)
index:6, transformer curve length: (198, 5), nfeatures stranformed: (262, 21)
index:7, transformer curve length: (200, 5), nfeatures stranformed: (262, 8)
index:8, transformer curve length: (148, 5), nfeatures stranformed: (262, 66)
index:9, transformer curve length: (3, 5), nfeatures stranformed: (262, 2)
index:10, transformer curve length: (63, 5), nfeatures stranformed: (262, 19)
index:11, transformer curve length: (78, 5), nfeatures stranformed: (262, 34)
model:Kernel Ridge, featurename: Canonical BOP, nestimators :13
index:0, transformer curve length: (18, 5), nfeatures stranformed: (262, 12)
index:1, transformer curve length: (51, 5), nfeatures stranformed: (262, 22)
index:2, transformer curve length: (145, 5), nfeatures stranformed: (262, 28)
index:3, transformer curve length: (206, 5), nfeatures stranformed: (262, 71)
index:4, transformer curve length: (100, 5), nfeatures stranformed: (262, 9)
index:5, transformer curve length: (150, 5), nfeatures stranformed: (262, 82)
index:6, transformer curve length: (55, 5), nfeatures stranformed: (262, 27)
index:7, transformer curve length: (122, 5), nfeatures stranformed: (262, 23)
index:8, transformer curve length: (112, 5), nfeatures stranformed: (262, 36)
index:9, transformer curve length: (163, 5), nfeatures stranformed: (262, 58)
index:10, transformer curve length: (59, 5), nfeatures stranformed: (262, 22)
index:11, transformer curve length: (171, 5), nfeatures stranformed: (262, 73)
index:12, transformer curve length: (36, 5), nfeatures stranformed: (262, 32)
model:Kernel Ridge, featurename: ACE no CNAV, nestimators :10
index:0, transformer curve length: (105, 5), nfeatures stranformed: (262, 43)
index:1, transformer curve length: (101, 5), nfeatures stranformed: (262, 55)
index:2, transformer curve length: (44, 5), nfeatures stranformed: (262, 20)
index:3, transformer curve length: (60, 5), nfeatures stranformed: (262, 24)
index:4, transformer curve length: (75, 5), nfeatures stranformed: (262, 44)
index:5, transformer curve length: (88, 5), nfeatures stranformed: (262, 20)
index:6, transformer curve length: (114, 5), nfeatures stranformed: (262, 46)
index:7, transformer curve length: (84, 5), nfeatures stranformed: (262, 50)
index:8, transformer curve length: (96, 5), nfeatures stranformed: (262, 24)
index:9, transformer curve length: (129, 5), nfeatures stranformed: (262, 63)
model:Kernel Ridge, featurename: ACE, nestimators :12
index:0, transformer curve length: (208, 5), nfeatures stranformed: (262, 155)
index:1, transformer curve length: (220, 5), nfeatures stranformed: (262, 130)
index:2, transformer curve length: (215, 5), nfeatures stranformed: (262, 121)
index:3, transformer curve length: (98, 5), nfeatures stranformed: (262, 30)
index:4, transformer curve length: (242, 5), nfeatures stranformed: (262, 121)
index:5, transformer curve length: (251, 5), nfeatures stranformed: (262, 211)
index:6, transformer curve length: (248, 5), nfeatures stranformed: (262, 71)
index:7, transformer curve length: (251, 5), nfeatures stranformed: (262, 50)
index:8, transformer curve length: (251, 5), nfeatures stranformed: (262, 207)
index:9, transformer curve length: (251, 5), nfeatures stranformed: (262, 145)
index:10, transformer curve length: (251, 5), nfeatures stranformed: (262, 72)
index:11, transformer curve length: (228, 5), nfeatures stranformed: (262, 118)
model:Kernel Ridge, featurename: 0.7dProjections 0.5OS BOP, nestimators :12
index:0, transformer curve length: (134, 5), nfeatures stranformed: (262, 65)
index:1, transformer curve length: (192, 5), nfeatures stranformed: (262, 61)
index:2, transformer curve length: (131, 5), nfeatures stranformed: (262, 51)
index:3, transformer curve length: (126, 5), nfeatures stranformed: (262, 41)
index:4, transformer curve length: (122, 5), nfeatures stranformed: (262, 28)
index:5, transformer curve length: (176, 5), nfeatures stranformed: (262, 59)
index:6, transformer curve length: (192, 5), nfeatures stranformed: (262, 41)
index:7, transformer curve length: (126, 5), nfeatures stranformed: (262, 66)
index:8, transformer curve length: (132, 5), nfeatures stranformed: (262, 39)
index:9, transformer curve length: (205, 5), nfeatures stranformed: (262, 124)
index:10, transformer curve length: (7, 5), nfeatures stranformed: (262, 6)
index:11, transformer curve length: (185, 5), nfeatures stranformed: (262, 101)
model:Kernel Ridge, featurename: 0.7spProjections 0.5OS BOP, nestimators :13
index:0, transformer curve length: (133, 5), nfeatures stranformed: (262, 83)
index:1, transformer curve length: (106, 5), nfeatures stranformed: (262, 43)
index:2, transformer curve length: (175, 5), nfeatures stranformed: (262, 101)
index:3, transformer curve length: (188, 5), nfeatures stranformed: (262, 119)
index:4, transformer curve length: (149, 5), nfeatures stranformed: (262, 64)
index:5, transformer curve length: (179, 5), nfeatures stranformed: (262, 71)
index:6, transformer curve length: (144, 5), nfeatures stranformed: (262, 80)
index:7, transformer curve length: (239, 5), nfeatures stranformed: (262, 138)
index:8, transformer curve length: (115, 5), nfeatures stranformed: (262, 31)
index:9, transformer curve length: (104, 5), nfeatures stranformed: (262, 47)
index:10, transformer curve length: (72, 5), nfeatures stranformed: (262, 30)
index:11, transformer curve length: (177, 5), nfeatures stranformed: (262, 83)
index:12, transformer curve length: (205, 5), nfeatures stranformed: (262, 81)
model:Kernel Ridge, featurename: atomic no CNAV, nestimators :8
index:0, transformer curve length: (8, 5), nfeatures stranformed: (262, 1)
index:1, transformer curve length: (8, 5), nfeatures stranformed: (262, 2)
index:2, transformer curve length: (8, 5), nfeatures stranformed: (262, 1)
index:3, transformer curve length: (7, 5), nfeatures stranformed: (262, 1)
index:4, transformer curve length: (7, 5), nfeatures stranformed: (262, 1)
index:5, transformer curve length: (7, 5), nfeatures stranformed: (262, 2)
index:6, transformer curve length: (6, 5), nfeatures stranformed: (262, 1)
index:7, transformer curve length: (8, 5), nfeatures stranformed: (262, 2)
model:Kernel Ridge, featurename: dataset no CNAV, nestimators :10
index:0, transformer curve length: (13, 5), nfeatures stranformed: (262, 4)
index:1, transformer curve length: (13, 5), nfeatures stranformed: (262, 7)
index:2, transformer curve length: (12, 5), nfeatures stranformed: (262, 5)
index:3, transformer curve length: (12, 5), nfeatures stranformed: (262, 8)
index:4, transformer curve length: (12, 5), nfeatures stranformed: (262, 8)
index:5, transformer curve length: (11, 5), nfeatures stranformed: (262, 6)
index:6, transformer curve length: (12, 5), nfeatures stranformed: (262, 7)
index:7, transformer curve length: (14, 5), nfeatures stranformed: (262, 10)
index:8, transformer curve length: (12, 5), nfeatures stranformed: (262, 5)
index:9, transformer curve length: (13, 5), nfeatures stranformed: (262, 10)
model:Kernel Ridge, featurename: 0.7dProjections 0.5OS BOP no CNAV, nestimators :10
index:0, transformer curve length: (48, 5), nfeatures stranformed: (262, 17)
index:1, transformer curve length: (51, 5), nfeatures stranformed: (262, 22)
index:2, transformer curve length: (35, 5), nfeatures stranformed: (262, 23)
index:3, transformer curve length: (45, 5), nfeatures stranformed: (262, 23)
index:4, transformer curve length: (48, 5), nfeatures stranformed: (262, 20)
index:5, transformer curve length: (32, 5), nfeatures stranformed: (262, 21)
index:6, transformer curve length: (49, 5), nfeatures stranformed: (262, 27)
index:7, transformer curve length: (28, 5), nfeatures stranformed: (262, 15)
index:8, transformer curve length: (47, 5), nfeatures stranformed: (262, 20)
index:9, transformer curve length: (50, 5), nfeatures stranformed: (262, 23)
model:Kernel Ridge, featurename: 0.7spProjections 0.5OS BOP no CNAV, nestimators :10
index:0, transformer curve length: (42, 5), nfeatures stranformed: (262, 30)
index:1, transformer curve length: (52, 5), nfeatures stranformed: (262, 47)
index:2, transformer curve length: (44, 5), nfeatures stranformed: (262, 28)
index:3, transformer curve length: (48, 5), nfeatures stranformed: (262, 45)
index:4, transformer curve length: (32, 5), nfeatures stranformed: (262, 28)
index:5, transformer curve length: (34, 5), nfeatures stranformed: (262, 27)
index:6, transformer curve length: (49, 5), nfeatures stranformed: (262, 26)
index:7, transformer curve length: (42, 5), nfeatures stranformed: (262, 27)
index:8, transformer curve length: (51, 5), nfeatures stranformed: (262, 41)
index:9, transformer curve length: (52, 5), nfeatures stranformed: (262, 42)
model:Kernel Ridge, featurename: SOAP_specific_small, nestimators :10
index:0, transformer curve length: (251, 5), nfeatures stranformed: (262, 107)
index:1, transformer curve length: (251, 5), nfeatures stranformed: (262, 250)
index:2, transformer curve length: (251, 5), nfeatures stranformed: (262, 74)
index:3, transformer curve length: (251, 5), nfeatures stranformed: (262, 135)
index:4, transformer curve length: (251, 5), nfeatures stranformed: (262, 139)
index:5, transformer curve length: (251, 5), nfeatures stranformed: (262, 102)
index:6, transformer curve length: (251, 5), nfeatures stranformed: (262, 164)
index:7, transformer curve length: (251, 5), nfeatures stranformed: (262, 154)
index:8, transformer curve length: (49, 5), nfeatures stranformed: (262, 43)
index:9, transformer curve length: (251, 5), nfeatures stranformed: (262, 142)
model:Kernel Ridge, featurename: SOAP_specific_small no CNAV, nestimators :10
index:0, transformer curve length: (46, 5), nfeatures stranformed: (262, 19)
index:1, transformer curve length: (57, 5), nfeatures stranformed: (262, 31)
index:2, transformer curve length: (41, 5), nfeatures stranformed: (262, 17)
index:3, transformer curve length: (42, 5), nfeatures stranformed: (262, 18)
index:4, transformer curve length: (52, 5), nfeatures stranformed: (262, 17)
index:5, transformer curve length: (64, 5), nfeatures stranformed: (262, 24)
index:6, transformer curve length: (45, 5), nfeatures stranformed: (262, 29)
index:7, transformer curve length: (49, 5), nfeatures stranformed: (262, 15)
index:8, transformer curve length: (35, 5), nfeatures stranformed: (262, 19)
index:9, transformer curve length: (44, 5), nfeatures stranformed: (262, 25)
model:Kernel Ridge, featurename: Canonical ACE no CNAV, nestimators :10
index:0, transformer curve length: (41, 5), nfeatures stranformed: (262, 6)
index:1, transformer curve length: (41, 5), nfeatures stranformed: (262, 10)
index:2, transformer curve length: (41, 5), nfeatures stranformed: (262, 9)
index:3, transformer curve length: (42, 5), nfeatures stranformed: (262, 14)
index:4, transformer curve length: (42, 5), nfeatures stranformed: (262, 6)
index:5, transformer curve length: (41, 5), nfeatures stranformed: (262, 8)
index:6, transformer curve length: (42, 5), nfeatures stranformed: (262, 5)
index:7, transformer curve length: (42, 5), nfeatures stranformed: (262, 5)
index:8, transformer curve length: (41, 5), nfeatures stranformed: (262, 10)
index:9, transformer curve length: (41, 5), nfeatures stranformed: (262, 10)
model:Kernel Ridge, featurename: Canonical BOP no CNAV, nestimators :64
index:0, transformer curve length: (41, 5), nfeatures stranformed: (262, 17)
index:1, transformer curve length: (42, 5), nfeatures stranformed: (262, 13)
index:2, transformer curve length: (41, 5), nfeatures stranformed: (262, 10)
index:3, transformer curve length: (41, 5), nfeatures stranformed: (262, 8)
index:4, transformer curve length: (41, 5), nfeatures stranformed: (262, 14)
index:5, transformer curve length: (41, 5), nfeatures stranformed: (262, 15)
index:6, transformer curve length: (42, 5), nfeatures stranformed: (262, 30)
index:7, transformer curve length: (41, 5), nfeatures stranformed: (262, 11)
index:8, transformer curve length: (41, 5), nfeatures stranformed: (262, 13)
index:9, transformer curve length: (41, 5), nfeatures stranformed: (262, 9)
index:10, transformer curve length: (41, 5), nfeatures stranformed: (262, 17)
index:11, transformer curve length: (41, 5), nfeatures stranformed: (262, 20)
index:12, transformer curve length: (41, 5), nfeatures stranformed: (262, 15)
index:13, transformer curve length: (41, 5), nfeatures stranformed: (262, 26)
index:14, transformer curve length: (42, 5), nfeatures stranformed: (262, 13)
index:15, transformer curve length: (41, 5), nfeatures stranformed: (262, 15)
index:16, transformer curve length: (41, 5), nfeatures stranformed: (262, 11)
index:17, transformer curve length: (42, 5), nfeatures stranformed: (262, 9)
index:18, transformer curve length: (41, 5), nfeatures stranformed: (262, 12)
index:19, transformer curve length: (41, 5), nfeatures stranformed: (262, 11)
index:20, transformer curve length: (42, 5), nfeatures stranformed: (262, 12)
index:21, transformer curve length: (42, 5), nfeatures stranformed: (262, 12)
index:22, transformer curve length: (41, 5), nfeatures stranformed: (262, 7)
index:23, transformer curve length: (41, 5), nfeatures stranformed: (262, 12)
index:24, transformer curve length: (41, 5), nfeatures stranformed: (262, 14)
index:25, transformer curve length: (40, 5), nfeatures stranformed: (262, 13)
index:26, transformer curve length: (41, 5), nfeatures stranformed: (262, 20)
index:27, transformer curve length: (42, 5), nfeatures stranformed: (262, 7)
index:28, transformer curve length: (42, 5), nfeatures stranformed: (262, 11)
index:29, transformer curve length: (41, 5), nfeatures stranformed: (262, 27)
index:30, transformer curve length: (41, 5), nfeatures stranformed: (262, 15)
index:31, transformer curve length: (41, 5), nfeatures stranformed: (262, 9)
index:32, transformer curve length: (42, 5), nfeatures stranformed: (262, 9)
index:33, transformer curve length: (42, 5), nfeatures stranformed: (262, 17)
index:34, transformer curve length: (40, 5), nfeatures stranformed: (262, 19)
index:35, transformer curve length: (40, 5), nfeatures stranformed: (262, 14)
index:36, transformer curve length: (42, 5), nfeatures stranformed: (262, 27)
index:37, transformer curve length: (41, 5), nfeatures stranformed: (262, 9)
index:38, transformer curve length: (41, 5), nfeatures stranformed: (262, 7)
index:39, transformer curve length: (41, 5), nfeatures stranformed: (262, 32)
index:40, transformer curve length: (42, 5), nfeatures stranformed: (262, 10)
index:41, transformer curve length: (41, 5), nfeatures stranformed: (262, 7)
index:42, transformer curve length: (41, 5), nfeatures stranformed: (262, 14)
index:43, transformer curve length: (41, 5), nfeatures stranformed: (262, 11)
index:44, transformer curve length: (41, 5), nfeatures stranformed: (262, 10)
index:45, transformer curve length: (41, 5), nfeatures stranformed: (262, 12)
index:46, transformer curve length: (41, 5), nfeatures stranformed: (262, 10)
index:47, transformer curve length: (42, 5), nfeatures stranformed: (262, 19)
index:48, transformer curve length: (41, 5), nfeatures stranformed: (262, 13)
index:49, transformer curve length: (42, 5), nfeatures stranformed: (262, 13)
index:50, transformer curve length: (42, 5), nfeatures stranformed: (262, 11)
index:51, transformer curve length: (41, 5), nfeatures stranformed: (262, 11)
index:52, transformer curve length: (41, 5), nfeatures stranformed: (262, 16)
index:53, transformer curve length: (42, 5), nfeatures stranformed: (262, 7)
index:54, transformer curve length: (41, 5), nfeatures stranformed: (262, 11)
index:55, transformer curve length: (42, 5), nfeatures stranformed: (262, 17)
index:56, transformer curve length: (41, 5), nfeatures stranformed: (262, 12)
index:57, transformer curve length: (42, 5), nfeatures stranformed: (262, 22)
index:58, transformer curve length: (41, 5), nfeatures stranformed: (262, 12)
index:59, transformer curve length: (42, 5), nfeatures stranformed: (262, 12)
index:60, transformer curve length: (40, 5), nfeatures stranformed: (262, 22)
index:61, transformer curve length: (42, 5), nfeatures stranformed: (262, 6)
index:62, transformer curve length: (35, 5), nfeatures stranformed: (262, 12)
index:63, transformer curve length: (24, 5), nfeatures stranformed: (262, 6)
model:Kernel Ridge, featurename: SOAP_canonicalW_small, nestimators :10
index:0, transformer curve length: (198, 5), nfeatures stranformed: (262, 16)
index:1, transformer curve length: (198, 5), nfeatures stranformed: (262, 8)
index:2, transformer curve length: (200, 5), nfeatures stranformed: (262, 92)
index:3, transformer curve length: (195, 5), nfeatures stranformed: (262, 40)
index:4, transformer curve length: (199, 5), nfeatures stranformed: (262, 111)
index:5, transformer curve length: (199, 5), nfeatures stranformed: (262, 51)
index:6, transformer curve length: (198, 5), nfeatures stranformed: (262, 86)
index:7, transformer curve length: (198, 5), nfeatures stranformed: (262, 39)
index:8, transformer curve length: (195, 5), nfeatures stranformed: (262, 27)
index:9, transformer curve length: (196, 5), nfeatures stranformed: (262, 107)
model:Kernel Ridge, featurename: SOAP_canonicalW_small no CNAV, nestimators :10
index:0, transformer curve length: (2, 5), nfeatures stranformed: (262, 1)
index:1, transformer curve length: (24, 5), nfeatures stranformed: (262, 13)
index:2, transformer curve length: (19, 5), nfeatures stranformed: (262, 11)
index:3, transformer curve length: (6, 5), nfeatures stranformed: (262, 3)
index:4, transformer curve length: (25, 5), nfeatures stranformed: (262, 15)
index:5, transformer curve length: (21, 5), nfeatures stranformed: (262, 11)
index:6, transformer curve length: (25, 5), nfeatures stranformed: (262, 14)
index:7, transformer curve length: (29, 5), nfeatures stranformed: (262, 16)
index:8, transformer curve length: (24, 5), nfeatures stranformed: (262, 16)
index:9, transformer curve length: (2, 5), nfeatures stranformed: (262, 1)

In [19]:
problematic = savedFCresults[(ModelName, 'atomic no CNAV')][4]

In [20]:
optimal_regressors[(ModelName, 'atomic no CNAV')]

VotingRegressor(estimators=[('0',
                             Pipeline(steps=[['feature_selection',
                                              FunctionTransformer(func=<function filter_features at 0x7fee8d8b5c10>,
                                                                  kw_args={'learning_curve':                                      train1     test1  \
MagpieData mean GSmagmom           0.144313  0.146840
Structure                          0.127471  0.138823
MagpieData maximum Row             0.125671  0.142002
MagpieData minimum AtomicWeight    0.123107  0.141536
MagpieData mode NsValence          0.115461...
MagpieData minimum AtomicWeight  0.147183  0.144261
Structure                        0.134221  0.131155
MagpieData maximum MeltingT      0.137975  0.125466
Mag                              0.147515  0.142368
MagpieData avg_dev Row           0.146598  0.139062
MagpieData mode GSmagmom         0.147410  0.138883
MagpieData mode NUnfilled        0.150883  0.138520  ,
                                                                           'remove_structure': True})],
                                             ('scaler', StandardScaler()),
                                             ('regressor',
                                              KernelRidge(alpha=1.0, degree=2,
                                                          kernel='polynomial'))]))])

In [21]:
problematic_estimator = optimal_regressors[(ModelName, 'atomic no CNAV')].estimators.pop(4)

In [22]:
problematic_estimator[1].named_steps.feature_selection.transform(X)

KeyError: "None of [Index(['MagpieData mean AtomicWeight'], dtype='object')] are in the [columns]"

In [23]:
DS.Features['atomic no CNAV'][problematic_estimator[1].named_steps.feature_selection.kw_args['learning_curve'].index]

,MagpieData mean AtomicWeight,Structure,MagpieData maximum AtomicWeight,MagpieData minimum MeltingT,MagpieData mode AtomicWeight,MagpieData mode NValence,Mag
Fe_pv4Mo_sv20.C36-ABBBB.FM,89.274167,3,95.960,1811.0,95.960,6.0,1
Fe_pv15Mo_sv38.R-AAAABBBBBBB.NM,84.606698,4,95.960,1811.0,95.960,6.0,0
Fe_pv2Mo_sv11.mu-BBABB.FM,89.788462,9,95.960,1811.0,95.960,6.0,1
Fe_pv8Mo_sv22.sigma-BBBAB.NM,85.262667,10,95.960,1811.0,95.960,6.0,0
Fe_pv2Mo_sv11.mu-BBBBA.NM,89.788462,9,95.960,1811.0,95.960,6.0,0
...,...,...,...,...,...,...,...
Fe_pv8Mo_sv16.C36-BAABB.NM,82.588333,3,95.960,1811.0,95.960,6.0,0
Fe_pv30.sigma.FM,55.845000,10,55.845,1811.0,55.845,8.0,1
Fe_pv6.C15.FM,55.845000,2,55.845,1811.0,55.845,8.0,1
Mo_sv8.A15.NM,95.960000,0,95.960,2896.0,95.960,6.0,0
Mo_sv6.C15.NM,95.960000,2,95.960,2896.0,95.960,6.0,0

In [24]:
DS.Features['atomic no CNAV'][problematic.index]

,MagpieData mean AtomicWeight,Structure,MagpieData maximum AtomicWeight,MagpieData minimum MeltingT,MagpieData mode AtomicWeight,MagpieData mode NValence,Mag,random,MagpieData avg_dev AtomicWeight
Fe_pv4Mo_sv20.C36-ABBBB.FM,89.274167,3,95.960,1811.0,95.960,6.0,1,0.461308,11.143056
Fe_pv15Mo_sv38.R-AAAABBBBBBB.NM,84.606698,4,95.960,1811.0,95.960,6.0,0,0.465851,16.280206
Fe_pv2Mo_sv11.mu-BBABB.FM,89.788462,9,95.960,1811.0,95.960,6.0,1,0.374388,10.444142
Fe_pv8Mo_sv22.sigma-BBBAB.NM,85.262667,10,95.960,1811.0,95.960,6.0,0,0.767237,15.689422
Fe_pv2Mo_sv11.mu-BBBBA.NM,89.788462,9,95.960,1811.0,95.960,6.0,0,0.698486,10.444142
...,...,...,...,...,...,...,...,...,...
Fe_pv8Mo_sv16.C36-BAABB.NM,82.588333,3,95.960,1811.0,95.960,6.0,0,0.883622,17.828889
Fe_pv30.sigma.FM,55.845000,10,55.845,1811.0,55.845,8.0,1,0.859332,0.000000
Fe_pv6.C15.FM,55.845000,2,55.845,1811.0,55.845,8.0,1,0.329511,0.000000
Mo_sv8.A15.NM,95.960000,0,95.960,2896.0,95.960,6.0,0,0.249109,0.000000
Mo_sv6.C15.NM,95.960000,2,95.960,2896.0,95.960,6.0,0,0.382767,0.000000

In [25]:
problematic_estimators

{('Kernel Ridge', 'atomic'): [],
 ('Kernel Ridge', 'dataset'): [],
 ('Kernel Ridge', 'Canonical ACE'): [],
 ('Kernel Ridge', 'Canonical BOP'): [],
 ('Kernel Ridge', 'ACE no CNAV'): [],
 ('Kernel Ridge', 'ACE'): [],
 ('Kernel Ridge', '0.7dProjections 0.5OS BOP'): [],
 ('Kernel Ridge', '0.7spProjections 0.5OS BOP'): [],
 ('Kernel Ridge', 'atomic no CNAV'): [],
 ('Kernel Ridge', 'dataset no CNAV'): [],
 ('Kernel Ridge', '0.7dProjections 0.5OS BOP no CNAV'): [],
 ('Kernel Ridge', '0.7spProjections 0.5OS BOP no CNAV'): [],
 ('Kernel Ridge', 'SOAP_specific_small'): [],
 ('Kernel Ridge', 'SOAP_specific_small no CNAV'): [],
 ('Kernel Ridge', 'Canonical ACE no CNAV'): [],
 ('Kernel Ridge', 'Canonical BOP no CNAV'): [],
 ('Kernel Ridge', 'SOAP_canonicalW_small'): [],
 ('Kernel Ridge', 'SOAP_canonicalW_small no CNAV'): []}

In [26]:
cleanFCresults = {}

In [29]:
for (modelname, featurename), list_problem_index  in problematic_estimators:
    cleanFCresults[(modelname, featurename)] = []
    if len(list_problem_index) < 0:
        continue
    for

SyntaxError: invalid syntax (1746470960.py, line 5)