In [1]:
import sys
import pandas as pd
import numpy as np
sys.path.append('/home/storage/fortimtb/CuadernoTrabajo/bopfoxfeaturizer/')
from BopFoxFeaturizer.brief_summary_parser import StructSummaryParser

In [2]:
evcurves = pd.read_json('evcurves.json', orient='index',typ='series')

In [3]:
evcurvegoodness = pd.read_json('goodness.json', orient='index', typ='series')

In [4]:
dataset = pd.read_pickle('Descriptors/CRCOW_INITIAL_NSC_CANONICAL_HISTCUTOFF_WUBIND.pkl')

In [5]:
indexofgoodsamples = pd.Index([(theindex) for theindex, thecurve in evcurvegoodness.items() if True in thecurve.values()])

In [6]:
dataset.loc[indexofgoodsamples]

,NSC_U_bind,NSC_U_bond_atom,NSC_U_bond_atom_list,NSC_moments,NSC_an,NSC_bn,NSC_SIGMA,NSC_Ainf,NSC_Binf
Co_pv6W_sv6.C14-BBA.FM,-80.856962,-80.867484,"[-4.7080372603, -4.7080372603, -4.7080372603, ...","[[0.0, 1.30409, -0.634205, 4.08953, -4.29737, ...","[[0.0, -0.48632200000000003, -0.22576999999999...","[[0.0, 1.14197, 1.26307, 1.51045, 1.71511, 1.7...","[[1.0, 0.2234485429, -0.4825601876, -0.2584779...","[-0.3731942763, -0.3731942763, -0.3731942763, ...","[1.6701575742, 1.6701575742, 1.6701575742, 1.6..."
Co_pv6W_sv6.C14-BBA.NM,-80.856962,-80.867484,"[-4.7080372603, -4.7080372603, -4.7080372603, ...","[[0.0, 1.30409, -0.634205, 4.08953, -4.29737, ...","[[0.0, -0.48632200000000003, -0.22576999999999...","[[0.0, 1.14197, 1.26307, 1.51045, 1.71511, 1.7...","[[1.0, 0.2234485429, -0.4825601876, -0.2584779...","[-0.3731942763, -0.3731942763, -0.3731942763, ...","[1.6701575742, 1.6701575742, 1.6701575742, 1.6..."
Cr_pv6W_sv2.D0_19-A3B.FM,-43.360131,-43.361886,"[-5.4806086023, -5.4811963856, -5.4806085931, ...","[[0.0, 1.55611, -0.46190499999999995, 4.3839, ...","[[0.0, -0.296833, -0.469329, -0.400833, -0.563...","[[0.0, 1.24744, 1.08305, 1.15153, 1.18244, 1.2...","[[1.0, 0.3247286078, 0.1725968745, 0.162067082...","[-0.3921285149, -0.3921284943, -0.3921151566, ...","[1.207557651, 1.207557661, 1.2075644356, 1.207..."
Cr_pv6W_sv2.D0_19-A3B.NM,-43.360131,-43.361886,"[-5.4806086023, -5.4811963856, -5.4806085931, ...","[[0.0, 1.55611, -0.46190499999999995, 4.3839, ...","[[0.0, -0.296833, -0.469329, -0.400833, -0.563...","[[0.0, 1.24744, 1.08305, 1.15153, 1.18244, 1.2...","[[1.0, 0.3247286078, 0.1725968745, 0.162067082...","[-0.3921285149, -0.3921284943, -0.3921151566, ...","[1.207557651, 1.207557661, 1.2075644356, 1.207..."
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM,-176.835252,-176.880388,"[-5.6501359701, -5.6501359701, -5.6501359701, ...","[[0.0, 1.6417299999999997, -0.514678, 4.64595,...","[[0.0, -0.313498, -0.0932309, -0.316523, -0.13...","[[0.0, 1.2813, 1.04399, 1.22413, 1.20185, 1.29...","[[1.0, 0.1388541893, -0.0230533713, -0.1054042...","[-0.1818035272, -0.1818035272, -0.1818035272, ...","[1.309312511, 1.309312511, 1.309312511, 1.3093..."
...,...,...,...,...,...,...,...,...,...
Cr_pv8Co_pv10W_sv12.sigma-BCCBA.FM,-185.714437,-185.759573,"[-6.3159512876, -6.3159512876, -6.3159512876, ...","[[0.0, 2.09979, -0.70091, 7.96301, -4.98935, 3...","[[0.0, -0.3338, 0.0748999, -0.0867996, -0.1575...","[[0.0, 1.44907, 1.25741, 1.49043, 1.49345, 1.4...","[[1.0, 0.1132604053, 0.024849493, -0.115723623...","[-0.16314406, -0.1631440601, -0.16314406, -0.1...","[1.4404333058, 1.4404333058, 1.4404333057, 1.4..."
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM,-172.647509,-172.692645,"[-5.0447105202, -5.0447105202, -5.0447105202, ...","[[0.0, 1.34753, -0.454488, 3.32921, -2.3634, 1...","[[0.0, -0.337275, -0.124542, -0.254523, -0.055...","[[0.0, 1.16083, 1.00465, 1.17859, 1.15633, 1.2...","[[1.0, 0.1102975231, -0.1285716329, -0.1663508...","[-0.1381249288, -0.1381249288, -0.1381249288, ...","[1.2522940218, 1.2522940218, 1.2522940218, 1.2..."
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM,-172.647509,-172.692645,"[-5.0447105202, -5.0447105202, -5.0447105202, ...","[[0.0, 1.34753, -0.454488, 3.32921, -2.3634, 1...","[[0.0, -0.337275, -0.124542, -0.254523, -0.055...","[[0.0, 1.16083, 1.00465, 1.17859, 1.15633, 1.2...","[[1.0, 0.1102975231, -0.1285716329, -0.1663508...","[-0.1381249288, -0.1381249288, -0.1381249288, ...","[1.2522940218, 1.2522940218, 1.2522940218, 1.2..."
Co_pv13W_sv16.chi-ABAB.NM,-190.58612,-190.824469,"[-5.3382566115, -5.3382566114, -5.3382566114, ...","[[0.0, 1.39375, -0.697376, 4.37561, -4.33507, ...","[[0.0, -0.500358, -0.0628219, -0.437898, -0.25...","[[0.0, 1.18057, 1.22284, 1.25595, 1.24353, 1.1...","[[1.0, 0.22350674649999996, -0.0824312448, -0....","[-0.2832830566, -0.2600184893, -0.2600184893, ...","[1.2674474534, 1.304822969, 1.304822969, 1.304..."
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM,-176.835252,-176.880388,"[-5.6501359701, -5.6501359701, -5.6501359701, ...","[[0.0, 1.6417299999999997, -0.514678, 4.64595,...","[[0.0, -0.313498, -0.0932309, -0.316523, -0.13...","[[0.0, 1.2813, 1.04399, 1.22413, 1.20185, 1.29...","[[1.0, 0.1388541893, -0.0230533713, -0.1054042...","[-0.1818035272, -0.1818035272, -0.1818035272, ...","[1.309312511, 1.309312511, 1.309312511, 1.3093..."

In [7]:
BS = StructSummaryParser(ForceMakeBS=True).BriefSummary

In [8]:
BS

,,B,E0,V,deltak,encut,fit,ncrash,nelem,xc,B0,V0,atom_A,atom_B,atom_C,num_atom_A,num_atom_B,num_atom_C,num_atoms
index,,,,,,,,,,,,,,,,,,,
Co_pv6W_sv6.C14-BBA.FM,bulk C14-BBA.FM,293.907391 GPa,-10.000427,13.175678 A,0.020,400,murnaghan volume_relaxed,0,2,PBE-PAW,293.907391,13.175678,Co_pv,W_sv,,6,6,0,12.0
Co_pv6W_sv6.C14-BBA.NM,bulk C14-BBA,293.949578 GPa,-10.000427,13.175679 A,0.020,400,murnaghan volume_relaxed,0,2,PBE-PAW,293.949578,13.175679,Co_pv,W_sv,,6,6,0,12.0
Cr_pv6W_sv2.D0_19-A3B.FM,bulk D0_19-A3B.FM,244.993002 GPa,-10.002413,13.098145 A,0.020,400,murnaghan volume_relaxed,0,2,PBE-PAW,244.993002,13.098145,Cr_pv,W_sv,,6,2,0,8.0
Cr_pv6W_sv2.D0_19-A3B.NM,bulk D0_19-A3B,248.338396 GPa,-10.002452,13.093819 A,0.020,400,murnaghan volume_relaxed,0,2,PBE-PAW,248.338396,13.093819,Cr_pv,W_sv,,6,2,0,8.0
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM,bulk sigma-CBAAC.FM,243.415325 GPa,-10.003732,13.525828 A,0.020,400,murnaghan volume_relaxed,0,3,PBE-PAW,243.415325,13.525828,Cr_pv,Co_pv,W_sv,16,4,10,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM,bulk sigma-BAACA.FM,251.093896 GPa,-9.988760,13.189987 A,0.020,400,murnaghan volume_relaxed,0,3,PBE-PAW,251.093896,13.189987,Cr_pv,Co_pv,W_sv,20,2,8,30.0
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM,bulk sigma-BAACA,251.071094 GPa,-9.988760,13.189913 A,0.020,400,murnaghan volume_relaxed,0,3,PBE-PAW,251.071094,13.189913,Cr_pv,Co_pv,W_sv,20,2,8,30.0
Co_pv13W_sv16.chi-ABAB.NM,bulk chi-ABAB,263.749012 GPa,-9.988843,14.051746 A,0.020,400,murnaghan volume_relaxed,0,2,PBE-PAW,263.749012,14.051746,Co_pv,W_sv,,13,16,0,29.0
Co_pv13W_sv16.chi-ABAB.FM,bulk chi-ABAB.FM,426.930807 GPa,-9.993120,14.075905 A,0.020,400,murnaghan volume_relaxed,0,2,PBE-PAW,426.930807,14.075905,Co_pv,W_sv,,13,16,0,29.0
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM,bulk sigma-CBAAC,237.775710 GPa,-9.997783,13.488365 A,0.020,400,murnaghan volume_relaxed,0,3,PBE-PAW,237.775710,13.488365,Cr_pv,Co_pv,W_sv,16,4,10,30.0

In [9]:
BS.loc[indexofgoodsamples]

,,B,E0,V,deltak,encut,fit,ncrash,nelem,xc,B0,V0,atom_A,atom_B,atom_C,num_atom_A,num_atom_B,num_atom_C,num_atoms
Co_pv6W_sv6.C14-BBA.FM,bulk C14-BBA.FM,293.907391 GPa,-10.000427,13.175678 A,0.020,400,murnaghan volume_relaxed,0,2,PBE-PAW,293.907391,13.175678,Co_pv,W_sv,,6,6,0,12.0
Co_pv6W_sv6.C14-BBA.NM,bulk C14-BBA,293.949578 GPa,-10.000427,13.175679 A,0.020,400,murnaghan volume_relaxed,0,2,PBE-PAW,293.949578,13.175679,Co_pv,W_sv,,6,6,0,12.0
Cr_pv6W_sv2.D0_19-A3B.FM,bulk D0_19-A3B.FM,244.993002 GPa,-10.002413,13.098145 A,0.020,400,murnaghan volume_relaxed,0,2,PBE-PAW,244.993002,13.098145,Cr_pv,W_sv,,6,2,0,8.0
Cr_pv6W_sv2.D0_19-A3B.NM,bulk D0_19-A3B,248.338396 GPa,-10.002452,13.093819 A,0.020,400,murnaghan volume_relaxed,0,2,PBE-PAW,248.338396,13.093819,Cr_pv,W_sv,,6,2,0,8.0
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.FM,bulk sigma-CBAAC.FM,243.415325 GPa,-10.003732,13.525828 A,0.020,400,murnaghan volume_relaxed,0,3,PBE-PAW,243.415325,13.525828,Cr_pv,Co_pv,W_sv,16,4,10,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cr_pv8Co_pv10W_sv12.sigma-BCCBA.FM,bulk sigma-BCCBA.FM,261.601104 GPa,-9.985958,13.099315 A,0.020,400,murnaghan volume_relaxed,0,3,PBE-PAW,261.601104,13.099315,Cr_pv,Co_pv,W_sv,8,10,12,30.0
Cr_pv20Co_pv2W_sv8.sigma-BAACA.FM,bulk sigma-BAACA.FM,251.093896 GPa,-9.988760,13.189987 A,0.020,400,murnaghan volume_relaxed,0,3,PBE-PAW,251.093896,13.189987,Cr_pv,Co_pv,W_sv,20,2,8,30.0
Cr_pv20Co_pv2W_sv8.sigma-BAACA.NM,bulk sigma-BAACA,251.071094 GPa,-9.988760,13.189913 A,0.020,400,murnaghan volume_relaxed,0,3,PBE-PAW,251.071094,13.189913,Cr_pv,Co_pv,W_sv,20,2,8,30.0
Co_pv13W_sv16.chi-ABAB.NM,bulk chi-ABAB,263.749012 GPa,-9.988843,14.051746 A,0.020,400,murnaghan volume_relaxed,0,2,PBE-PAW,263.749012,14.051746,Co_pv,W_sv,,13,16,0,29.0
Cr_pv16Co_pv4W_sv10.sigma-CBAAC.NM,bulk sigma-CBAAC,237.775710 GPa,-9.997783,13.488365 A,0.020,400,murnaghan volume_relaxed,0,3,PBE-PAW,237.775710,13.488365,Cr_pv,Co_pv,W_sv,16,4,10,30.0